### ISSUE TITLE
[REGRESSION] zimdump -C (checksum verification) is broken

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#10]
```
$ zimdump -C /var/www/download.kiwix.org/zim/other/ekopedia_fr_all_novid_2017-09.zim
invalid checksum in zim file
kelson@download:/tmp$ zimdump.old -C /var/www/download.kiwix.org/zim/other/ekopedia_fr_all_novid_2017-09.zim
checksum ok
```

zimdump.old is 2 years old but I do not know the exact version.

**Comment by kelson42** [comment]
@mgautierfr I have tested with the last nightly and the result is still wrong but differently.
```
$ ./zimdump -C /var/www/download.kiwix.org/zim/other/ekopedia_fr_all_novid_2017-09.zim
no checksum
$ zimdump.old -C /var/www/download.kiwix.org/zim/other/ekopedia_fr_all_novid_2017-09.zim
checksum ok
```

It is "impossible" this ZIM file has no checksum as this file is really recent.

**Comment by mgautierfr** [comment]
Can you test again ?
`zimdump` returns me "checksum ok" for ekopedia_fr_all_novid_2017-09.zim

I've no change on zim-tools side and on libzim I've got only things about the blob sizes (not related to checksum).
