### ISSUE TITLE
zimwriterfs internal error: redirect not found

### ISSUE THREAD

**Issue by tim-moody** [openzim/zim-tools#101]
running:

sudo docker build -t zimwriterfs zimwriterfs_config
time sudo docker run -it -v $(pwd)/articles:/articles -v $(pwd)/output:/output zimwriterfs

which runs

#!/bin/bash
zimwriterfs \
--title="CDC Extract" \
--description="Centers for Disease Control Web Site" \
--creator="www.cdc.gov" \
--publisher="Tim Moody" \
--tags="IIAB;Medical;CDC" \
--language="eng" \
--welcome="www.cdc.gov/index.html" \
--favicon="www.cdc.gov/images/home/favicon.ico" \
--withFullTextIndex \
--verbose \
/articles \
/output/cdc_en_novids_2017-10.zim \
 | tee /output/outp.log

on extract from www.cdc.gov 

processes for 70 minutes and
yields following messages and terminates

isArticleIndexer running: yes
isArticleIndexer running: no
sort 195094 directory entries (aid)
remove invalid redirects from 195094 directory entries
sort 195072 directory entries (url)
set index
translate redirect aid to index
internal error: redirect aid www.cdc.gov/globalhealth/healthprotection/ghsb/gphi/partnership.htm not found

but file exists
root@iiab-devel:~/zimwriterfs# ll articles/www.cdc.gov/globalhealth/healthprotection/ghsb/gphi/partnership.htm
-rw-r--r-- 1 root root 1606 Oct 24 14:19 articles/www.cdc.gov/globalhealth/healthprotection/ghsb/gphi/partnership.htm

**Comment by kelson42** [comment]
@asashnov Would be happy if this error message coudl be done quickly so we can finally close that ticket.

**Comment by asashnov** [comment]
Currently, message is the following:
```
cd ~/oz/zim-tools/test

~/oz/zim-tools/build/src/zimwriterfs/zimwriterfs  \
  --title="CDC Extract" --description="Centers for Disease Control Web Site" \
  --creator="www.cdc.gov" --publisher="Tim Moody" --tags="IIAB;Medical;CDC" \
   --language="eng"  --welcome="www.cdc.gov/index.html" \
   --favicon="www.cdc.gov/images/home/favicon.ico" \
   --withFullTextIndex   --verbose  \
   data/broken-html-redirects \
   cdc_en_novids_2017-10.zim 

Visiting directory data/broken-html-redirects
Visiting directory data/broken-html-redirects/www.cdc.gov
Visiting directory data/broken-html-redirects/www.cdc.gov/images
Visiting directory data/broken-html-redirects/www.cdc.gov/images/home
Visiting directory data/broken-html-redirects/www.cdc.gov/globalhealth
Visiting directory data/broken-html-redirects/www.cdc.gov/globalhealth/healthprotection
Visiting directory data/broken-html-redirects/www.cdc.gov/globalhealth/healthprotection/ghs
Visiting directory data/broken-html-redirects/www.cdc.gov/globalhealth/healthprotection/ghsb
Visiting directory data/broken-html-redirects/www.cdc.gov/globalhealth/healthprotection/ghsb/gphi
T:1; A:16; RA:2; CA:13; UA:1; FA:1; IA:1; C:0; CC:0; UC:0; WC:0
T:1; Waiting for workers
T:1; ResolveRedirectIndexes
Resolve redirect
Invalid redirection A/www.cdc.gov/globalhealth/healthprotection/ghsb/gphi/partnership.htm redirecting to (missing) w/w.cdc.gov/globalhealth/healthprotection/ghs/index.htm
T:1; Set article indexes
set index
T:1; Resolve mimetype
T:1; create title index
T:1; 17 title index created
T:1; 2 clusters created
T:1; write zimfile :
T:1;  write mimetype list
T:1;  write directory entries
T:1;  write url prt list
T:1;  write title index
T:1;  write cluster offset list
T:1;  write header
T:1;  write checksum
T:1; rename tmpfile to final one.
T:1; finish
```

**Comment by asashnov** [comment]
It's irrelevant to the code, but may be still interesting in some sence. 
www.cdc.gov bounces between HTTP and HTTPS using same index.html filename so we can have clash on disk files while downloading.

<details><summary>Details (spoiler)</summary>

```

HTTPS redirects to HTTP:

$ curl https://www.cdc.gov/globalhealth/healthprotection/ghs/
<meta http-equiv="refresh" content="0; URL='http://www.cdc.gov/globalhealth/healthprotection/ghs/index.html'" />


HTTP redirects to HTTPS index.html:

$ curl -I http://www.cdc.gov/globalhealth/healthprotection/ghs/index.html
HTTP/1.1 301 Moved Permanently
Server: AkamaiGHost
Content-Length: 0
Location: https://www.cdc.gov/globalhealth/healthprotection/ghs/index.html
Date: Tue, 15 Sep 2020 14:29:30 GMT
Connection: keep-alive


HTTPS index.html outputs HTTP 2.0 protocol:

$ curl -I https://www.cdc.gov/globalhealth/healthprotection/ghs/index.html
HTTP/2 200 
content-type: text/html
srv: 4
access-control-allow-origin: *
x-ua-compatible: IE=edge
date: Tue, 15 Sep 2020 14:29:53 GMT
strict-transport-security: max-age=31536000 ; includeSubDomains ; preload
```
</details>

**Comment by kelson42** [comment]
I guess we ca close this ticket.
