### ISSUE TITLE
I don't **fox** issues :) but no I didn't fix anything related to this. actually the UI code hasn't been touched in a long time. I'll mark it as needing a reprocase and we'll look at it when someone encounters it.

### ISSUE THREAD

**Issue by Pyanz60** [openzim/zim-tools#107]
I don't **fox** issues :) but no I didn't fix anything related to this. actually the UI code hasn't been touched in a long time. I'll mark it as needing a reprocase and we'll look at it when someone encounters it.

_Originally posted by @rgaudin in https://github.com/openzim/zimfarm/issues/387#issuecomment-588214634_

**Comment by kelson42** [comment]
I don’t get what this ticket is about.
