### ISSUE TITLE
Add one line descriptions of each tool

### ISSUE THREAD

**Issue by legoktm** [openzim/zim-tools#110]
I'm preparing zim-tools for packaging in Debian, which wants each binary to have a man page. It would help me (and users primarily) if each tool had a one line description of its purpose in the help output. Some already do, but these are missing them:

* zimbench
* zimdump
* zimsearch
* zimsplit

**Comment by legoktm** [comment]
Here are the descriptions I went with for now:
* benchmark a ZIM file
* dump a ZIM file
* search a ZIM file
* split a ZIM file into smaller parts

**Comment by kelson42** [comment]
@legoktm 
* zimbench - Benchmark a ZIM file reading speed
* zimdump - Inspect & dump a ZIM file content
* zimsearch - Search content in a ZIM file
* zimsplit - Split smartly a ZIM file in smaller parts
