### ISSUE TITLE
LICENSE is GPLv3 but most files are GPLv2+

### ISSUE THREAD

**Issue by legoktm** [openzim/zim-tools#112]
All of the files in src/ are GPLv2+ (except one LGPL file) but LICENSE is GPLv3+. This is not a problem of course since v2+ is compatible with v3+, but maybe LICENSE should have the GPLv2 in it, or the files should have their headers updated to GPLv3+?

For reference:
```
$ licensecheck src 
src/arg.h: LGPL (v2.1 or later)
src/meson.build: *No copyright* UNKNOWN
src/progress.h: GPL (v2 or later)
src/version.h: GPL (v2 or later)
src/zimbench.cpp: GPL (v2 or later)
src/zimcheck.cpp: GPL (v2 or later)
src/zimdiff.cpp: GPL (v2 or later)
src/zimdump.cpp: GPL (v2 or later)
src/zimpatch.cpp: GPL (v2 or later)
src/zimrecreate.cpp: GPL (v2 or later)
src/zimsearch.cpp: GPL (v2 or later)
src/zimsplit.cpp: GPL (v2 or later)
```

**Comment by kelson42** [comment]
This should be GPL3+, everything we do, except for the libzim is GPL3+.
