### ISSUE TITLE
zimwriterfs creates invalid ZIM files

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-tools#116]
zimwriterfs `1.3.9` and `1.3.10` create ZIM files in a non-atomic manner : the file is named/renamed to `xxx.zim` while data is being added to it.

This is a forbidden behavior (discussed in several tickets). Main consequence is that tools watching creation of ZIM files in scrapers are triggered too early.

Version `1.3.7` and `1.3.8` are not affected.

**Comment by kelson42** [comment]
@mgautierfr To me this looks like again to a weak/unclear finalisation process like already reported here https://github.com/openzim/libzim/issues/348 or https://github.com/openzim/libzim/issues/331.

**Comment by mgautierfr** [comment]
I'm really surprise about the behavior. The rename is made at the last end of `finishZimCreation` (https://github.com/openzim/libzim/blob/master/src/writer/creator.cpp#L238). You can even see that we close the file descriptor of the temporary file (`*.zim.tmp`) before renaming it.

**Comment by rgaudin** [comment]
Could you find out which version of libzim was packed in those two zimwriterfs versions?

**Comment by mgautierfr** [comment]
The `versions.py` file in kiwix-build is our friend here.

The first build of `zimwriterfs-1.3.9` has been made with `libzim-6.1.0` . (https://github.com/kiwix/kiwix-build/commit/bd546fe33e6a80e3648e16e9f80cb62e2a422841#diff-1ab225aa70820615603a523677fbb53e)
`libzim-6.1.0` was indeed not atomic and we fix this with `6.1.3`
From https://github.com/kiwix/kiwix-build/commit/59b03181932db739269a5ac20c332a6e211d7b7e#diff-1ab225aa70820615603a523677fbb53e, the first build `zimwriterfs` with the correct version of libzim is `zimwriterfs-1.3.10-1`

**Comment by rgaudin** [comment]
Great. I confirm it's OK with 1.3.10-4. Thanks for checking.
