### ISSUE TITLE
zimcheck wrong/incomprehensible error message

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#124]
```
$ zimcheck  /media/backup/download.kiwix.org/zim/ted/ted_en_playlist-581_2020-07.zim
[INFO] Checking zim file /media/backup/download.kiwix.org/zim/ted/ted_en_playlist-581_2020-07.zim
[INFO] Verifying Internal Checksum.. 
  [INFO] Internal checksum found correct
[INFO] Searching for metadata entries..
[INFO] Searching for Favicon..
[INFO] Searching for main page..
[INFO] Verifying Articles' content.. 
[INFO] Searching for redundant articles..
  Verifying Similar Articles for redundancies..
[ERROR] Invalid internal links found :
  assets/videojs/lang/zh-CN.json (idx 129) and assets/videojs/lang/zh-Hans.json (idx 131)
  assets/videojs/lang/zh-Hant.json (idx 133) and assets/videojs/lang/zh-TW.json (idx 135)
  assets/videojs/lang/ba.json (idx 59) and assets/videojs/lang/hr.json (idx 91)
[INFO] Overall Test Status: Fail
[INFO] Total time taken by zimcheck: 5 seconds.
```

I don't understand at all what goes wrong. If internal links are wrong I should get an error message which tell me:
* wrong URL
* in which article it is

**Comment by kelson42** [comment]
@MiguelRocha I suspect here (at least) a bug around the mgmt of the error type based on `errorString` and `TestType`. `errorString` should not be an array, this can so easily be out-of-sync with `TestType`. We should have a more robust solution base on a map or anything else, I let you judge.

**Comment by kelson42** [comment]
I believe here the message should be about same content... and if this is confirmed, probably this should be a WARNING, not an ERROR.

**Comment by rgaudin** [comment]
Check the source and, contrary to what's stated on the line above, content is not **very similar** but **identical**.
Also believe this should be a passing warning as the spec doesn't prohibit duplicating resources.

Very useful info for scraper makers though ; although in this particular example, probably not worth fixing.

**Comment by MiguelRocha** [comment]
Yes your are right there is a bug in the error reporting and the current solution is indeed very error prone. The "error" should be "Redundant data found". I'll come up with a solution.

**Comment by kelson42** [comment]
I seems that the problem of non-matching error message is still there, see https://github.com/openzim/warc2zim/issues/21:
```
[ERROR] Missing metadata entries :
  Entry A/www.bouquineux.com/pdf/Tchekhov-La_Steppe.pdf is empty
  Entry A/www.bouquineux.com/pdf/Tchekhov-Trois_ans.pdf is empty
  Entry A/www.bouquineux.com/pdf/Tolstoi-Contes_et_nouvelles_-_Tome_III.pdf is empty
```

I don't believe we have a metadata problem here.

**Comment by MiguelRocha** [comment]
@mgautierfr true, its not a metadata test. I suggest the following msg for the emptyness check:

`[ERROR] There are empty articles:`

What do you think?

**Comment by kelson42** [comment]
@MiguelRocha Just `[ERROR] Empty articles:` please
