### ISSUE TITLE
Incorrect Mime-type list in an old ZIM file?

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#126]
```
zimdump info /media/backup/download.kiwix.org/zim/stack_exchange/stackoverflow.com_en_all_2019-02.zim 
Exception: Error getting mimelists.
```

What wonders me a lot is that this file is 18 months old. It should be OK.

**Comment by kelson42** [comment]
@MiguelRocha Could you please make the investigation of what go wrong here please?

**Comment by kelson42** [comment]
@MiguelRocha Have you find out what goes wrong with this file?

**Comment by ttsiodras** [comment]
Seconded - I built kiwix-tools from source, and...

- version 3.1.2 of kiwix-serve reports: 

    $ kiwix-serve stackoverflow.com_en_all_2019-02.zim
    Unable to add the ZIM file 'stackoverflow.com_en_all_2019-02.zim' to the internal library

- zimcheck v2.0.0 reports: 

    $ zimcheck stackoverflow.com_en_all_2019-02.zim 
    [INFO] Checking zim file stackoverflow.com_en_all_2019-02.zim
    Error getting mimelists.

The MD5 of the downloaded file is fine (verified against original, took a while to MD5 134GB, but checksum was correct).

I also checked the `kiwix-tools` that are part of Arch Linux - same reports.
Note that the tools work fine with many other ZIM files - it's only this ZIM file that fails.

**Comment by MiguelRocha** [comment]
The mimetype list in this file is huge:

(taken from a debug session in libzim structures:)
```
$10 = std::vector of length 81, capacity 128 = {
  "%5D--%5BADDRESS%7CADDRESS_ID%20(PK);STREET;ZIPCODE;CITY%5D",
  "*%3E%5BAddress%5D",
  "**png",
  "-%3C%3E%5BPromotion%5D",
  "-%3C%3E%5BPromotion%5D,%20%5BItem%5D-%3C%3E%5BPromotedPurchaseOption%5D",
  "-%3E%5Bnull%5D,%5Bmain%5Dcircle_1-%3E%5BaCircle%2810%29%5D,%5BaCircle%2810%29%5Dcenter-%3E%5BaPoint%287%208%29%5D,%5BaPoint%285%205%29%5D",
  "0",
  "1",
  "1%3E%5BPaymentMethod%5D",
  "3806431",
  "380643111639415,",
  "ImageServer",
  "application/font-ttf",
  "application/font-woff",
  "application/javascript",
  "application/octet-stream",
  "application/octet-stream+xapian",
  "application/pdf",
  "application/vnd.ms-fontobject",
  "ashx",
  "asp",
  "aspx",
  "bmp",
  "cfm",
  "cgi",
  "com",
  "do",
  "download",
  "eps",
  "gif%60%60",
  "gif%7D",
  "gifs",
  "gifv",
  "gif~",
  "ico",
  "image/gif",
  "image/jpeg",
  "image/png",
  "image/svg+xml",
  "image/tiff",
  "j",
  "jp",
  "jpg\"",
  "jpg#",
  "jpg##",
  "jpg%20",
  "jpg%3Fv%3D0",
  "jpg%5C",
  "jpg%60",
  "jpg%60%60",
  "jpg%C2%A8",
  "jpg%E2%80%8B",
  "jpg'",
  "jpg)",
  "jpg*",
  "jpg,",
  "jpg-",
  "jpg1",
  "jpg100",
  "jpg3",
  "jpg4",
  "jpg7866ef51",
  "jpg:",
  "jpg;",
  "jpg<br",
  "jpg<p",
  "jpg>",
  "jpgBlockquote",
  "jpgF",
  "jpg]",
  "jpga",
  "jpgas",
  "jpgb",
  "jpgd",
  "jpge",
  "jpgh",
  "jpgj",
  "jpgl",
  "jpgm",
  "jpgmy",
  "jpgw"
}

```

And most of its values do not seem to be valid mimetypes at all. There was some issue while creating this zimfile.

**Comment by kelson42** [comment]
@MiguelRocha So https://github.com/openzim/libzim/pull/425 would detect the problem?

**Comment by kelson42** [comment]
@veloman-yunkan Assigning you to help closing the ticket. Have to reask the same question: So openzim/libzim#425 would detect the problem?

**Comment by veloman-yunkan** [comment]
> So openzim/libzim#425 would detect the problem?

@kelson42 Not in its current form

**Comment by kelson42** [comment]
OK, so keeping the ticket open.

**Comment by veloman-yunkan** [comment]
> `Exception: Error getting mimelists.`

The weird MIME-type list in this (old-style) ZIM file (with the dirent-pointer table placed right after the MIME-type list) exceeds the limit of 944 (1024 - *header_size*) bytes imposed on new-style ZIM files (where the dirent-pointer table is placed at the end). Old-style ZIM-files didn't have such a limit, but the [new code for reading the MIME-type list](https://github.com/openzim/libzim/blob/6.3.0/src/fileimpl.cpp#L149-L158) makes no distinction:

>    // libzim write zims files two ways :
>    // - The old way by putting the urlPtrPos just after the mimetype.
>    // - The new way by putting the urlPtrPos at the end of the zim files.
>    //   In this case, the cluster data are always at 1024 bytes offset and we know that
>    //   mimetype list is before this.
>    // 1024 seems to be a good maximum size for the mimetype list, **even for the "old" way.**
>    auto endMimeList = std::min(header.getUrlPtrPos(), static_cast<zim::offset_type>(1024));

So fixing this issue should be independent of openzim/libzim#376 (though, the latter should be implemented taking this one into account).
