### ISSUE TITLE
Incomprehensible ZIM check error about internal links

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#146]
```
$ zimcheck  gutenberg_ar_all_2020-07.zim 
...
[ERROR] Invalid internal links found:
  The following links:
- 
- 
(A/) were not found in article A/Home.html
...
```

I don't really understand this message. Why we have two empty links?

**Comment by MiguelRocha** [comment]
@kelson42 The article A/Home.html has the following:

```
            <h1><a href="" data-l10n-id="top-title">Project Gutenberg Library</a></h1>
            <h2><a href="" data-l10n-id="sub-title">The first producer of free ebooks</a></h2>
```

I also find the message incomprehensible. I think that for these cases we should have something like:
`2 empty links found in article A/Home.html`

What do you think?

**Comment by kelson42** [comment]
@MiguelRocha Agree.
