### ISSUE TITLE
zimwriterfs error (Assertion failed at .... libzim_release/src/writer/creator.cpp:297)

### ISSUE THREAD

**Issue by go2tom42** [openzim/zim-tools#157]
Using zim-tools_linux-x86_64-2.0.0-1 binaries on ubuntu 20.04

zimdump'ed wikispecies_en_all_maxi_2020-06.zim

`zimdump dump --dir=./wikispecies_en_all_maxi_2020-06 wikispecies_en_all_maxi_2020-06.zim`

Then immediately tried to remake a zim file

`zimwriterfs --welcome=A/Main_Page --favicon=-/favicon.png --language=eng --title=mytest --description=ThisIsATest --creator=self --publisher=self --inflateHtml --verbose . my_project.zim` 

If runs for a while and ends with this

> T:202; A:1166000; RA:1; CA:58; UA:1165941; FA:1165972; IA:0; C:3094; CC:0; UC:3094; WC:0
> T:202; A:1166850; RA:1; CA:59; UA:1166790; FA:1166821; IA:0; C:3096; CC:0; UC:3096; WC:0
> T:203; Waiting for workers
> T:203; ResolveRedirectIndexes
> Resolve redirect
> T:203; Set article indexes
> set index
> T:203; Resolve mimetype
> T:206; create title index
> T:207; 1166852 title index created
> T:207; 3098 clusters created
> T:207; write zimfile :
> T:208;  write mimetype list
> 
> Assertion failed at ../../SOURCE/libzim_release/src/writer/creator.cpp:297
>  lseek(out_fd, 0, SEEK_CUR)[470937] < CLUSTER_BASE_OFFSET[1024]
> [0x43aba4]
> [0x433591]
> [0x4371d0]
> [0x41ffc8]
> [0x40a84c]
> [0x94cac6]
> [0x94d0b5]
> [0x40e769]
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  
> Assertion failed at ../../SOURCE/libzim_release/src/writer/creator.cpp:297
>  lseek(out_fd, 0, SEEK_CUR)[470937] < CLUSTER_BASE_OFFSET[1024]
> Aborted

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan @MiguelRocha Or is that a bug in the libzim? A regression?

**Comment by MiguelRocha** [comment]
Seems to something wrong with the mime types (too long?)

@go2tom42 can you share the full output and/or `wikispecies_en_all_maxi_2020-06.zim`

I was unable to reproduce with `wikispecies_en_all_maxi_2020-06.zim`

**Comment by go2tom42** [comment]
Full output?

File is from 
https://archive.org/details/wikispecies_en_all_maxi_2020-06.zim

MD5 for wikispecies_en_all_maxi_2020-06.zim matches one listed on archive.org

Here is output from running zimdump
https://pastebin.com/Uxv5iY3q

Here is output from running zimwriterfs
https://pastebin.com/S1sSyMVP

**Comment by asashnov** [comment]
> Then immediately tried to remake a zim file

@go2tom42 Did you mean running 'zimwriterfs' in different console before 'zimdump' has completed?

**Comment by go2tom42** [comment]
> 
> 
> > Then immediately tried to remake a zim file
> 
> @go2tom42 Did you mean running 'zimwriterfs' in different console before 'zimdump' has completed?

No, I waited for zimdump to finish.

**Comment by kelson42** [comment]
@asashnov Any news here?

**Comment by asashnov** [comment]
Where to get zim-tools binaries now?
The page https://wiki.openzim.org/wiki/Zimdump points to 404 https://www.openzim.org/download/

**Comment by kelson42** [comment]
Download.kiwix.org, but you shoukd test agInst our own code IMO.

**Comment by kelson42** [comment]
@asashnov Any news here?

**Comment by asashnov** [comment]
The problem here is that `zimwriterfs` kind of 'cycles' when the output .zim file directory matches with HTML input source directory. Here is my experiment:

It takes about 20 seconds to repack a small 33 mb file:

Extract some .zim file first:
```
$ ~/oz/zim-tools/build/src/zimdump dump --dir=wikipedia_en_100_maxi \
   ZIM.files/wikipedia_en_100_maxi_2020-05.zim
```
(33 Mb, md5sum starts with 366d22bd)

Pack normally, with resulting .zim outside of input HTML directory:
```
~/oz/zim-tools/build/src/zimwriterfs/zimwriterfs \
 --welcome=A/index --favicon=-/favicon --language=eng --title=mytest \
 --description=ThisIsATest --creator=self --publisher=self --inflateHtml \
 --verbose ~/oz/wikipedia_en_100_maxi \
  ~/oz/result.zim  \
   2>&1 | tee ~/oz/repacked_outside_input_HTML.txt
```

The above works fine, about 20 seconds.

Now try to reproduce this bug, putting the resulting .zim inside input HTML folder:
```
~/oz/zim-tools/build/src/zimwriterfs/zimwriterfs \
  --welcome=A/index --favicon=-/favicon --language=eng --title=mytest \
  --description=ThisIsATest --creator=self --publisher=self --inflateHtml \
 --verbose ~/oz/wikipedia_en_100_maxi \
 ~/oz/wikipedia_en_100_maxi/result.zim  \
   2>&1 | tee ~/oz/repacked_inside_input_HTML.txt
```

This time it hangs for a long while, so I stop it by Ctrl+C.

**Comment by asashnov** [comment]
When compare `zimwriterfs` output, in case of using HTML source directory as an output directory two additional lines of output printed:

```
Visiting directory /home/alex/oz/wikipedia_en_100_maxi/result_title.idx.tmp
Visiting directory /home/alex/oz/wikipedia_en_100_maxi/result.idx.tmp
```
Then the process just gets stuck, without any significant difference in output.


So, to fix this issue, we should either:
* prohibit to use input HTML directory as an output for .zim file;
* or note and skip temporary files while iterating the directory.

@kelson42 which way to choose?

**Comment by asashnov** [comment]
> Note, that the process stuck next time anyway....

Because of this, I think it's still usefull to see where exactly zimwriterfs get stuck when processing a directory with zimwriterfs temporary files inside.

**Comment by asashnov** [comment]
I suspected in this issue the user experienced running out of free disk space, because their output (from https://pastebin.com/S1sSyMVP) contains repeatedly:

```
T:93; A:484000; RA:1; CA:58; UA:483941; FA:483972; IA:0; C:1455; CC:0; UC:1455; WC:0
T:93; A:485000; RA:1; CA:58; UA:484941; FA:484972; IA:0; C:1457; CC:0; UC:1457; WC:0
T:93; A:486000; RA:1; CA:58; UA:485941; FA:485972; IA:0; C:1459; CC:0; UC:1459; WC:0
```

But it is not a case. No repeated output on lack of free space (#177).
