### ISSUE TITLE
Zimcheck (was: Creator) should check that we have no redirect loop

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#161]
To avoid this kind of bug https://github.com/kiwix/kiwix-tools/issues/207

**Comment by mgautierfr** [comment]
Yes, it would be better in zimcheck.
It the creator, it would be implemented by a check anyway (no real way to detect that nicely).

**Comment by shashwat1002** [comment]
Hi, I am just exploring the codebase right now hoping to contribute. 
I had questions about this issue: 
- would you like this feature to be implemented as a separate test? 
- I followed [https://github.com/kiwix/kiwix-tools/issues/207](kiwix/kiwix-tools#207), is something similar expected here? 
- in what circumstances do you want the test to run?

If you think that I haven't read something that I should've read up on please point me in the right direction.
Any help or suggestion is appreciated :)

**Comment by kelson42** [comment]
@shashwat1002 Thank you for reaching to us. This should be a test in `zimcheck`. The link you have given is broken, not sure to what you want to refer.

**Comment by shashwat1002** [comment]
@kelson42 
I just fixed the link. 
and the parameters should just be `const zim::Archive& archive, ErrorLogger& reporter` yeah?

**Comment by kelson42** [comment]
@shashwat1002 thx, can not tell you much about the details of the implementation. When you have something ready, just make a PR so we can review it.

**Comment by shashwat1002** [comment]
@veloman-yunkan , you talked about a more robust version of the check. Should I create a new issue or should I just refer to this while I work on that? 

@kelson42

**Comment by veloman-yunkan** [comment]
@shashwat1002 I don't mind about the bureaucratic side of the work. Please wait for and follow @kelson42's advice

**Comment by kelson42** [comment]
@shashwat1002 I'm not sure about where I talked about a "more robust" solution (if you talked about #515, this was a wrong lead, sorry). Can we close this ticket as you have implemented the feature?

**Comment by shashwat1002** [comment]
@kelson42 

This is what I'm talking about: https://github.com/openzim/zim-tools/pull/218#pullrequestreview-591054518

**Comment by kelson42** [comment]
@shashwat1002 You mean using a stack to detect loops? I was under the impression this is what you already had done. But I'm under the impression this ticket is implemented and you want to do something better. In that case, close this ticket and open a new one.

**Comment by shashwat1002** [comment]
@kelson42  
that wasn't what I had done. 
My solution was simpler and reported a redirect loop if the number of chained redirects were more than 50

I would like to implement the stack based solution now, should I do it on this ticket?

**Comment by kelson42** [comment]
@shashwat1002 Sorry for my super late answer, but “yes”, such a PR would be really welcome!
