### ISSUE TITLE
Never-ending zimcheck run....

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#166]
With https://download.kiwix.org/zim/wikipedia/wikipedia_arz_all_maxi_2020-10.zim
```
$ zimcheck -D wikipedia_arz_all_maxi_2020-10.zim 
[INFO] Checking zim file wikipedia_arz_all_maxi_2020-10.zim
[INFO] Verifying Internal Checksum...
[INFO] Searching for metadata entries...
[INFO] Searching for Favicon...
[INFO] Searching for main page...
[INFO] Verifying Articles' content...
[INFO] Searching for redundant articles...
  Verifying Similar Articles for redundancies...
```

**Comment by kelson42** [comment]
@MiguelRocha I have to add this new urgent finding/bug. Was blocking the whole ZIM quarantine!

**Comment by MiguelRocha** [comment]
@kelson42 the cause for this may be that the code for this check is indeed very inefficient. I have some ideas that shouldn't take much effort to increase the performance here.

Also the --progress option can give us more feedback

**Comment by kelson42** [comment]
@MiguelRocha Have you found the root cause meanwhile?

**Comment by kelson42** [comment]
@veloman-yunkan Can you please have a look to this ticket?
