### ISSUE TITLE
zimdump: no option to list namespaces in .zim file

### ISSUE THREAD

**Issue by asashnov** [openzim/zim-tools#170]
Program: zimdump (for zim-tools)
Version: current master (243e869d)

There is no option to list namespaces from .zim file.

## Actual result:

```
$ ~/oz/zim-tools/build/src/zimdump --version
zimdump 2.0.0

$ ~/oz/zim-tools/build/src/zimdump --help

zimdump tool is used to inspect a zim file and also to dump its contents into the filesystem.

Usage:
  zimdump list [--details] [--idx=INDEX|([--url=URL] [--ns=N])] [--] <file>
  zimdump dump --dir=DIR [--ns=N] [--redirect] [--] <file>
  zimdump show (--idx=INDEX|(--url=URL [--ns=N])) [--] <file>
  zimdump info [--ns=N] [--] <file>
  zimdump -h | --help
  zimdump --version
```

## Expected result:

There should be an option which iterates every 'Directory Entry' in .zim file and print uniq list of discovered namespaces like:

```
$ zimdump list --namespaces
-
A
I
M
X
```

The output of this command can be used in further calls of `zimdump list` to specify `--ns=<?>` value.

**Comment by kelson42** [comment]
@mgautierfr Still not absolutly sure this is or will be a good idea to implement this. Do you see the value of this on a longer term?

**Comment by data-man** [comment]
Proposals.
Add some function to `zim::Archive`

1. `std::set<std::string> getNamespaces() const;` (or `std::unordered_set<std::string>`) 

or

2. `std::map<std::string, size_type> getNamespaces() const;` (or `std::unordered_map<std::string, size_type>`) with the number of articles in each namespace

**Comment by mgautierfr** [comment]
New libzim moved to the idea there is no more namespace. 
They are still used internally, but from the user perspective they are gone. All the user content is directly accessible without namespace.

So I don't think we need to add a way to list the namespaces.
But we may have to improve a bit zimdump to access "extra" data, as metadadata, indexes, ...

**Comment by kelson42** [comment]
I close this ticket as IMO this is not fitting anymore to the new libzim. New tickets might be open to specificly as for way to access "hidden" namespaces data.
