### ISSUE TITLE
zimdump list --ns=<N> doesn't work as a filter

### ISSUE THREAD

**Issue by asashnov** [openzim/zim-tools#171]
Program: zimdump (for zim-tools)
Version: current master (243e869)

## Actual result:

The output of those commands below are equal:

```
$ ~/oz/zim-tools/build/src/zimdump list ~/oz/ZIM.files/storybox_en_2020-05.zim | wc -l
591

$ ~/oz/zim-tools/build/src/zimdump list --ns=M ~/oz/ZIM.files/storybox_en_2020-05.zim | wc -l
591
```

## Expected result:

```
$ ~/oz/zim-tools/build/src/zimdump list --ns=M ~/oz/ZIM.files/storybox_en_2020-05.zim
Counter
Creator
Date
Description
Flavour
Language
Name
Publisher
Scraper
Source
Tags
Title
```

I expect --ns=<N> to work as a filter, listing entries only from the specified namespace, skipping the others.

**Comment by kelson42** [comment]
I believe I can confirm this problem I was already impacted myself. Is that easy to fix?

**Comment by kelson42** [comment]
@maneeshpm Would you like to look at this bug? This is a pretty anooying one for users.

**Comment by maneeshpm** [comment]
Sure @kelson42, I'll start working on this one.

**Comment by maneeshpm** [comment]
@kelson42 Even though we are providing the `--ns=` option, there is no handler for it in any of the zimdump subcmds. I could not find any function in libzim/archive.cpp that could directly help us filter by namespace. So I think we can add a condition like `if (path[0] != nsfilter) continue` if the ns filter is provided. Is there any better method?

**Comment by kelson42** [comment]
@veloman-yunkan Do you believe his is the proper way of doing?

**Comment by veloman-yunkan** [comment]
@maneeshpm I guess you missed the [`zim::Archive::findByPath()`](https://github.com/openzim/libzim/blob/a4330a57bcd3da6249f2ddddc71f4e456dd21c93/include/zim/archive.h#L279-L288) method:

```c++
      /** Find a range of entry starting with path.
       *
       * The path is the "long path". (Ie, with the namespace)
       *
       * @param path The path prefix to search for.
       * @return A range starting from the first entry starting with path
       *         and ending past the last entry.
       *         If no entry starts with `path`, begin == end.
       */
      EntryRange<EntryOrder::pathOrder>  findByPath(std::string path) const;
```

**Comment by maneeshpm** [comment]
Thanks for pointing it out @veloman-yunkan, I tried it, `findByPath()` throws a runtime error because when a namespace url like `A` is passed to this function, another function `zim::parseLongPath()` is called which throws a runtime error in such a case.
```c++
std::tuple<char, std::string> zim::parseLongPath(const std::string& longPath)
{
  /* Index of the namespace char; discard '/' from absolute paths */
  const unsigned int i = (longPath[0] == '/') ? 1 : 0;
  if (i + 2 >= longPath.size() || longPath[i] == '/' || longPath[i+1] != '/')
    throw std::runtime_error("Cannot parse path");
```
But modifying this function such that it returns the namespace along with an empty string as path when such a url is passed
```c++
std::tuple<char, std::string> zim::parseLongPath(const std::string& longPath)
{
  /* Index of the namespace char; discard '/' from absolute paths */
  const unsigned int i = (longPath[0] == '/') ? 1 : 0;
  if (i + 2 >= longPath.size() && longPath[i] != '/') 
    return std::make_tuple(longPath[i], "");
  if (i + 2 >= longPath.size() || longPath[i] == '/' || longPath[i+1] != '/')
    throw std::runtime_error("Cannot parse path");

```
After this modification:
```
$ zimdump list --ns=M khan-academy-videos_fr_amine_2020-06.zim                                                                                             
M/Counter
M/Creator
M/Date
M/Description
M/Flavour
M/Language
M/Name
M/Publisher
M/Scraper
M/Tags
M/Title
```
@kelson42 I believe this is the expected behavior.

**Comment by kelson42** [comment]
@maneeshpm Yes, seems to be the proper behaviour but you should not have to modify the libzim. I let you sort ot these details and the review with @veloman-yunkan

**Comment by kelson42** [comment]
@maneeshpm Please, prepare a PR (even in draft), it is not a good idea to work on code (review) base on the ticket.

**Comment by maneeshpm** [comment]
Ohk @kelson42, thanks for the information.
