### ISSUE TITLE
zimwriterfs should store its version and command line arguments into .zim as metadata

### ISSUE THREAD

**Issue by asashnov** [openzim/zim-tools#172]
zimwriterfs should store its version and command line arguments into .zim as metadata `ZimWriterFs` entry, for example:

```
Version: 2.0.0
Git revision: 243e869d
Command line: ../zim-tools_linux-x86_64-2.0.0-4/zimwriterfs --welcome=A/Main_sequence --favicon=-/favicon --language=eng --title=mytest  --description=ThisIsATest --creator=self --publisher=self --inflateHtml --verbose . my_project.zim
```

This is needed to debug and reproduce bugs in existing .zim files. For example, `wikispecies_en_all_maxi_2020-06.zim` (2.2 Gb, md5 starts with d14fb2c7) when extracted, contains a lot of unrecognized HTML redirect files:
```
-rw-r--r-- 1 user user     178 окт 28 21:20 A.Alfaro
-rw-r--r-- 1 user user     179 окт 28 21:20 A.Alibertis
-rw-r--r-- 1 user user     179 окт 28 21:20 A.A.Lise
-rw-r--r-- 1 user user     170 окт 28 21:20 Aalius
```

witn content (A.Alfaro):
```html
<!DOCTYPE html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="refresh" content="0;url=Anastasio_Alfaro" /><head><body></body></html>
```

If it is a bug, a separate issue should be created to discuss it.

But here I just want to notice that creator version and command line will help a lot.

PS. In my case it seems to be generated HTML redirects on unpacking, created by zimdump, as there is no any symlink in extracted directory, and in `zimdump list --details` that articles listed as 'redirect'.

**Comment by kelson42** [comment]
To me, what you mean is a default version of `--scraper` option. See "scraper" metadata https://wiki.openzim.org/wiki/Metadata#Keys. I don't think the whole command line is really useful. Can you do that?

**Comment by asashnov** [comment]
@kelson42 Do you mean that instead of my initial idea we can just add

`Packer` metadata with content `zimwriterfs 2.0.0` ?

It's still better than nothing. But it can be also in form:

```
Name: zimwriterfs
Version: 2.0.0
Arguments: ....
```

**Comment by kelson42** [comment]
@asashnov Yes, please implement "zimwriterfs 2.0.0" if not `--scraper` argument given.

**Comment by asashnov** [comment]
@kelson42 why `--scraper argument` matters at all?

M/Scraper - is the name of program which downloaded the content from web site to local disk (wget --mirror for example)
M/Packer   - is the program which packet downloaded directory into .zim file ("zimwriterfs 2.0.0")

If `--scraper argument` is not specified, `M/Scraper` should just be missing.
And `M/Packer` should be always present ("zimwriterfs <ver>") until another program is used to create .zim file.

**Comment by kelson42** [comment]
We stick to the spec https://wiki.openzim.org/wiki/Metadata. There is nothing like `M/Packer`. Please fix it quickly, so we can close the project.

**Comment by mgautierfr** [comment]
I arrive a bit after the battle, but it would be nice to have the libzim version used somewhere.
Most of the writer code is on libzim and so the same version of zimwriterfs may write pretty different zim files if it use different version of libzim.

It is also useful as mwoffliner use directly libzim and not zimwriterfs.

It will not be fixed with code in zimwriterfs, but it worth to discuss this somewhere to agree where to put this metadata.

**Comment by kelson42** [comment]
@mgautierfr I agree about the need. It is usefull to know more about the dependences (not only the libzim). I think this is not specific about zimwriterfs and even not to zim-tools. I would suggest that a ticket is created and that we implement such a feature somewhere, a pattern which could be then reused for other projects.

**Comment by asashnov** [comment]
Link to the new issue:
https://github.com/openzim/libzim/issues/452 - Gather informations about dependence libraries version
