### ISSUE TITLE
zimdump list --details works too long

### ISSUE THREAD

**Issue by asashnov** [openzim/zim-tools#173]
Version: current master (243e869d)

## Actual result:

```
$ ~/oz/zim-tools/build/src/zimdump list --details \
     wikispecies_en_all_maxi_2020-06.zim \
     > ~/oz/wikispecies_details.txt
```
Works for more than 15 minutes, the output size is 15 Mb at the moment.

Strace log for about 7 seconds of its run:

```
$ strace -p 12133  > strace.txt 2>&1
     Ctrl^C after about 7 seconds
```

[strace.txt](https://github.com/openzim/zim-tools/files/5458041/strace.txt)

I can't believe it really takes that long to extract all the 'Directory' clusters. I suspect some operations are did twice, for extracting every 'Directory' entry for example.

Need to profile and figure out how many times clusters are really extracted.

`zimdump list` without `--details` works quite fast, starts to print article names immediately.

## Expected result:

Unpacking clusters with directory entries should take that long.

## Additional info:

The process was finished within about two hours with 224 Mb of output.

**Comment by kelson42** [comment]
@asashnov I assume you have cutting edge version of both libzim and zim-tools?

**Comment by kelson42** [comment]
@asashnov I can not confirmed your measure. Here are my results made with my workstation 7 years old, ZIM file on a relatively slow hard-disk and output on `/dev/shm`. Cutting edge code of both libzim/zim-tools with a more recent ZIM file.

```
$ time zimdump list --details /media/backup/download.kiwix.org/zim/other/wikispecies_en_all_maxi_2020-10.zim > wikispecies_details.txt

real	2m20.250s
user	1m41.245s
sys	0m13.734s
$ls -la wikispecies_details.txt 
-rw-rw-r-- 1 kelson kelson 245169564 Okt 30 14:51 wikispecies_details.txt

```

To me there is no problem, I get what looks to be the same output in 2mn. So there is problem somewhere here, either you use quite old libzim or there is something else about your hardware/OS.

**Comment by asashnov** [comment]
I use libzim 6.1.8 (Jul 2020) because had a compilation problem with `master`.

**Comment by asashnov** [comment]
I confirm that the 'master' version of libzim and release (not debug) build works properly:

```
$ time ~/oz/zim-tools/build/src/zimdump list --details      ~/oz/ZIM.files/wikispecies_en_all_maxi_2020-06.zim/wikispecies_en_all_maxi_2020-06.zim      > ~/oz/wikispecies_details.txt

real	3m43,127s
user	2m24,825s
sys	0m36,346s
```

**Comment by kelson42** [comment]
Nice
