### ISSUE TITLE
zimwriterfs complains about glyphicons

### ISSUE THREAD

**Issue by tim-moody** [openzim/zim-tools#188]
on creating a zim zimwriterfs complains about missing glyphicons fonts, but they are not used by any of the html being added to zim.

**Comment by kelson42** [comment]
To pursue this ticket we will need:
* the version of zimwriterfs
* a problematic dataset
* the command line
* the output log

**Comment by tim-moody** [comment]
sorry.

I found it. bootstrap wants these files. (assets/bootstrap.min.css)
