### ISSUE TITLE
zimdump creates dandling symlink to favicon

### ISSUE THREAD

**Issue by asashnov** [openzim/zim-tools#191]
zim-tools 'master' (5ed81f87)

zimdump creates dandling symlink to favicon.

## Steps to reproduce

1. Create minimal .zim file:

```
$ ls -l ~/oz/zim-tools/test/data/minimal-content
total 8
-rw-r--r-- 1 alex alex 2725 сен 28 01:16 favicon.png
-rw-r--r-- 1 alex alex  153 сен 28 01:16 hello.html

~/oz/zim-tools/build/src/zimwriterfs/zimwriterfs \
   -w hello.html -f favicon.png -l en -t 'Test Minimal content' \
   -d 'This is a test' -c alex -p nobody --verbose \
   ~/oz/zim-tools/test/data/minimal-content \
   minimal.zim
```

2. Now extract this .zim:

```
$ ~/oz/zim-tools/build/src/zimdump dump --dir=min minimal.zim
```

3. Check the content of the resulting directory.

## Actual result

There is a dangling symlink in `-` folder for favicon file. In `I` the favicon is OK:

```
$ ls -l min/-
total 0
lrwxrwxrwx 1 alex alex 11 Nov 20 22:23 favicon -> favicon.png

$ ls -l min/I
total 4
-rw-r--r-- 1 alex alex 2725 Nov 20 22:23 favicon.png
```

## Expected result:

`min/-/favicon` should point to `../I/favicon.png` instead of just `favicon.png`

## Additional information

Kiwix desktop shows correctly the content of hello.html and favicon:

![Screenshot from 2020-11-20 22-18-36](https://user-images.githubusercontent.com/5078434/99816849-c1aac500-2b7e-11eb-85b2-5ff881f227ec.png)

```
$ ~/oz/zim-tools/build/src/zimdump list --details minimal.zim
url: favicon
	title:           favicon
	idx:             0
	namespace:       -
	type:            redirect
	redirect index:  2
	extra:           
url: hello.html
	title:           HTML title tag content
	idx:             1
	namespace:       A
	type:            article
	mime-type:       text/html
	article size:    153
	extra:           
url: favicon.png
	title:           favicon.png
	idx:             2
	namespace:       I
	type:            article
	mime-type:       image/png
	article size:    2725
	extra:           
```

**Comment by asashnov** [comment]
See also: https://github.com/openzim/libzim/pull/402 This PR already closed, in description:

>  There is a new getFaviconPath to implement, return the path of the favicon (scrapper doesn't have to add themselves the -/favicon redirection).

**Comment by kelson42** [comment]
@asashnov Can yu please quickly fix that?

**Comment by kelson42** [comment]
@asashnov We are curretly removing the namespaces... I guess the vug will be fixed by itself.

**Comment by kelson42** [comment]
@mgautierfr You confirm we can close this?

**Comment by mgautierfr** [comment]
On this specific issue (dandling symlink), we can close the issue.

However, what we called favicon is now illustration (It doesn't prevent existing favicon to be correctly writen if present)

**Comment by mgautierfr** [comment]
Worth to mention that for new zim file, as Illustration is part of metadata, zimdump will not create the corresponding file.
