### ISSUE TITLE
zimwriterfs 'Invalid redirection' for favicon when run with --uniqueNamespace option

### ISSUE THREAD

**Issue by asashnov** [openzim/zim-tools#192]
zim-tools 'master' (5ed81f87)
libzim 'master' (540bc34d5)

zimwriterfs doesn't include favicon when run with --uniqueNamespace option.

## Steps to reproduce

1. Pack the same content with and without `--uniqueNamespace` options
2. Compare the output of `zimwriterfs` and the resulting .zim files

## Actual result

`Invalid redirection -/favicon redirecting to (missing) I/favicon.png` error in the output;
There is no `-/favicon` redirect in resulting .zim file because redirect still generated for `I/favicon.png` and was not found.

## Expected result

When generated with `--uniqueNamespace` option `-/favicon` redirect should still persist in .zim file and points to `A/favicon.png`.

## Additional information

```
$ ~/oz/zim-tools/build/src/zimwriterfs/zimwriterfs \
  -w hello.html -f favicon.png -l en -t 'Test Minimal content' \
  -d 'This is a test' -c alex -p nobody --verbose  \
  ~/oz/zim-tools/test/data/minimal-content   minimal_without.zim
Visiting directory /home/alex/oz/zim-tools/test/data/minimal-content
T:0; A:15; RA:1; CA:13; UA:1; FA:1; IA:1; C:0; CC:0; UC:0; WC:1
T:0; Waiting for workers
T:1; ResolveRedirectIndexes
Resolve redirect
T:1; Set article indexes
set index
T:1; Resolve mimetype
T:1; create title index
T:1; 17 title index created
T:1; 2 clusters created
T:1; write zimfile :
T:1;  write mimetype list
T:1;  write directory entries
T:1;  write url prt list
T:1;  write title index
T:1;  write cluster offset list
T:1;  write header
T:1;  write checksum
T:1; rename tmpfile to final one.
T:1; finish

$ ~/oz/zim-tools/build/src/zimdump list --detail minimal_without.zim > without_uniq_namespace.txt

$ ~/oz/zim-tools/build/src/zimwriterfs/zimwriterfs \
  --uniqueNamespace  -w hello.html -f favicon.png -l en -t 'Test Minimal content'  \
  -d 'This is a test' -c alex -p nobody --verbose  \
  ~/oz/zim-tools/test/data/minimal-content  minimal.zim
Visiting directory /home/alex/oz/zim-tools/test/data/minimal-content
T:0; A:15; RA:1; CA:13; UA:1; FA:1; IA:1; C:0; CC:0; UC:0; WC:0
T:0; Waiting for workers
T:0; ResolveRedirectIndexes
Resolve redirect
Invalid redirection -/favicon redirecting to (missing) I/favicon.png
T:0; Set article indexes
set index
T:0; Resolve mimetype
T:0; create title index
T:0; 16 title index created
T:0; 2 clusters created
T:0; write zimfile :
T:0;  write mimetype list
T:0;  write directory entries
T:0;  write url prt list
T:0;  write title index
T:0;  write cluster offset list
T:0;  write header
T:0;  write checksum
T:0; rename tmpfile to final one.
T:0; finish

$ ~/oz/zim-tools/build/src/zimdump list --detail minimal.zim > with_uniq_namespace.txt
```

```
meld without_uniq_namespace.txt with_uniq_namespace.txt
```

![Screenshot from 2020-11-20 22-43-31](https://user-images.githubusercontent.com/5078434/99821643-e013bf00-2b84-11eb-8f9d-ba0ce1f9309c.png)

**Comment by mgautierfr** [comment]
The master of zim-tools now use the new api of libzim and we always create zim file "without" namespace (technically, namespace is hidden).

The option `--uniqueNamespace` is removed.
Do you have the same issue with the master branch ?

**Comment by kelson42** [comment]
Probably we should fix this issue by juste removing the —uniqueNamespace feaure?

**Comment by kelson42** [comment]
Option `--uniqueNamespace` has been removed with #196 and https://github.com/openzim/libzim/issues/527 will secure there is not metadata as redirect. Closing.
