### ISSUE TITLE
Zimcheck should be able to printout a machine-readable JSON

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#203]
We are currently deeply integrety the `zimcheck` in the Zimfarm and we the (still to be built) CMS.

If the ZIM check process is part of the Zimfarm process, the level of tolerance regarding errors/warnings is a duty of the CMS.

Therefore the `zimcheck` result will follow that path:
* Zimfarm worker runs zimcheck
* Zimcheck generates a json with all the results (levels, messages, exit code, ...)
* Zimfarm worker upload the json to the zimfarm
* CMS request the zimcheck results to the zimfarm
* CMS decides based on it what to do (publish, alert, throw away the ZIM, etc...)

This is why we need an additional option `--json_log=PATH` which in addition to what is written to the STDOUT/STDIN will write in json PATH the zimcheck output.

**Comment by kelson42** [comment]
@veloman-yunkan Would you be able to do this ticket as well please? This is relatively urgent.

**Comment by veloman-yunkan** [comment]
@kelson42 Yes, I can do that

**Comment by rgaudin** [comment]
What do you think about optionally writing this to stdout? When automating this, I am not interested in a text output so it makes more sense to receive this JSON as output and pipe that to wherever I need than to be forced to dump to a file and use it.

**Comment by kelson42** [comment]
OK, then just a boolean `--json` argument?

**Comment by rgaudin** [comment]
> OK, then just a boolean `--json` argument?

👍

**Comment by veloman-yunkan** [comment]
@rgaudin @kelson42 Can you provide several examples of JSON output expected from zimcheck?

**Comment by kelson42** [comment]
I don't have a typical output of zimcheck under my eyes, but I would like to have for each error/warning, the following infos:
* date
* log level
* message
* error code

To me this is an opportunity to use a proper logging framework like log4cxx, the json output being just a formatter of it.

We have currently a kind of log hierarchy, not sure how we should deal with that. I'm open to suggestions.

**Comment by mgautierfr** [comment]
> To me this is an opportunity to use a proper logging framework like log4cxx, the json output being just a formatter of it.

I don't know about log4cxx but yes, we should use a library and no reimplement json dumping ourselves.
If we use a tool that can also output to something else than json, we may use the option `--format=(json|human|xml|...)` to have a more generic way to set the output, without a lot of work on our side.

> We have currently a kind of log hierarchy, not sure how we should deal with that. I'm open to suggestions.

I don't think we need a hierarchy here. We can simply have a a list of error (each error having a error kind). It would be to the tool reading the json to regroupe/filter the way it fit best.

> Not sure as well if we should put an entry with the overall exit code value.

We should. It will simplify parsing of the output and marking zim as passing or not.
@rgaudin may want some more information.


I'm thinking of this kind of output (not fixed) :

```
{
   'file_name' : 'foo.zim',
   'date' : '2021-01-04', # hour ?
   'checks_run' : ['checksum', 'integrity', 'favicon', 'url_internal'],
   'zimcheck_version' : '2.1.0',
   'error_nb': 2,
   'warning_nb': 10,
   'status': false,
   'errors': [
     {
       'kind': 'favicon',
       'error_code' : 1, # We should set a error code for each possible error
       'message': 'Favicon is missing'
     },
     {
       'kind': 'url_internal',
       'error_code' : 2,
       'message': 'url foo.html in article bar.html is not found',
       'article': 'bar.html',  # Not sure we need this
       'url': 'foo.html' # Not sure we need this
     }
   ]
}
```

**Comment by rgaudin** [comment]
@mgautierfr looks good.

This will be passed directly to the CMS so @kelson42 may have more precise needs as this is where this output will be used.

To me the most important is to have this list of error code. 

I think having the number of *errors* broken down by `kind` would be much helpful as I already see use for this (`warc2zim`-created ZIMs would ignore duplicate errors for instance).

**Comment by kelson42** [comment]
Based on what has been proposed, I believe a bitt better:
```
{
   'file_name' : 'foo.zim',
   'file_uuid' : 'XYZ...',
   'date' : '2021-01-04T00:00', #ISO 8601
   'checks' : ['checksum', 'integrity', 'favicon', 'url_internal'],
   'zimcheck_version' : '2.1.0',
   'status': false,
   'logs': [
     {
       'check': 'favicon',
       'level': 'error',
       'code' : 1, # We should set a error code for each possible error
       'message': 'Favicon is missing',
       'url': 'foo.html'
     },
     {
       'check': 'url_internal',
       'level': 'warning',
       'code' : 2,
       'message': 'url foo.html in article bar.html is not found',
       'url': 'foo.html'
     }
   ]
}
```
@rgaudin I'm relatively against creating summary entries counting the entry by `level` or `code`. This should be done by the log  reader. Should be trivial.
