### ISSUE TITLE
Handle xmpp has external protocol

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#204]
```
- xmpp:user@tux.gr
(A/xmpp:user@tux.gr) were not found in article A/Οδηγός_χρήσης_irssi

```

See https://farm.openzim.org/pipeline/4661fdf51541d0e4b593eef5

**Comment by kelson42** [comment]
Same for the news: protocol

**Comment by kelson42** [comment]
Same for urn: protocol

**Comment by veloman-yunkan** [comment]
Are there real-world examples of the `urn:` scheme being used in links?

**Comment by kelson42** [comment]
Yes, all of this comes from real zimcheck errors on the zimfarm.
