### ISSUE TITLE
`meson build` requires libzim-dev version >= 6.3.0 (for ubuntu) which isn't available for ubuntu 20.04 LTS [Question]

### ISSUE THREAD

**Issue by shashwat1002** [openzim/zim-tools#217]
It seems that the required version of `libzim-dev` has only been packaged for ubuntu 20.10.
I am using ubuntu 20.04 LTS and the latest version for `libzim-dev` available here is `4.3.5-5ubuntu3`.

What would you recommend for installation of `libzim-dev`on ubuntu to conduct tests on `zom-tools` and to build it?

**Comment by kelson42** [comment]
The git master version
