### ISSUE TITLE
Print page name during zimcheck --main 

### ISSUE THREAD

**Issue by lidel** [openzim/zim-tools#219]
Would it be possible to print the name of the "main page" of the ZIM during `zimcheck --main` ?

For example [wikipedia_tr_all_maxi_2021-01.zim](https://download.kiwix.org/zim/wikipedia/wikipedia_tr_all_maxi_2021-01.zim) has main set to `Kullanıcı:The_other_Kiwix_guy/Landing`, so perhaps printing it like this:

```diff
$ zimcheck --main ./wikipedia_tr_all_maxi_2021-01.zim
  [INFO] Checking zim file ./wikipedia_tr_all_maxi_2021-01.zim
  [INFO] Searching for main page...
+ [INFO] Main page: Kullanıcı:The_other_Kiwix_guy/Landing
  [INFO] Overall Test Status: Pass
  [INFO] Total time taken by zimcheck: 0 seconds.
```

It would enable [ipfs/distributed-wikipedia-mirror](https://github.com/ipfs/distributed-wikipedia-mirror) to automatically set the correct landing page. 
It is not a hard blocker, but right now we need to eyeball it for every language by opening a ZIM file in some Kiwix reader. 

cc @kelson42

**Comment by kelson42** [comment]
@lidel `zimdump` is the proper tool for that:
```
$ zimdump info /tmp/pokepedia_fr_all_maxi_2019-05.zim
count-entries: 142378
uuid: 3b22e149-0d9a-4f0e-ba5a-420aa4650552
cluster count: 3677
checksum: ba148c887e7c47090ec16a2bcd138d0a
main page: 22308
favicon: 5

```

Does the index is useful? Or do you need the URL?

**Comment by lidel** [comment]
@kelson42 I need the URL (article name) – can I get that from index somehow?

**Comment by kelson42** [comment]
@lidel I believe `zimdump` should just print the main page url in place ont the index.
