### ISSUE TITLE
Unable to run automated tests

### ISSUE THREAD

**Issue by shashwat1002** [openzim/zim-tools#221]
After having built the project using
`meson . build`
`ninja -C build`

I want to run the automated tests, I go into the `build` directory and run `meson test`
I get the following message:
`ninja: no work to do.  `
`No tests defined.`

Am I missing something?

**Comment by shashwat1002** [comment]
An extension to this question, is there way to get the list of commands being run on the tests that are done when I push new code. 
I see more things when I push code than I do when I run the commands as written in the `README` and it's cumbersome to push code just to check whether it works.

**Comment by veloman-yunkan** [comment]
> After having built the project using
> `meson . build`
> `ninja -C build`
> 
> I want to run the automated tests, I go into the `build` directory and run `meson test`
> I get the following message:
> `ninja: no work to do. `
> `No tests defined.`
> 
> Am I missing something?

Do you have `googletest` installed?

**Comment by veloman-yunkan** [comment]
> An extension to this question, is there way to get the list of commands being run on the tests that are done when I push new code.
> I see more things when I push code than I do when I run the commands as written in the `README` and it's cumbersome to push code just to check whether it works.

Don't mind about possible failures of the CI while you are working on your PR. Those failures should be addressed after you consider the PR (mostly) completed.

**Comment by shashwat1002** [comment]
> > After having built the project using
> > `meson . build`
> > `ninja -C build`
> > I want to run the automated tests, I go into the `build` directory and run `meson test`
> > I get the following message:
> > `ninja: no work to do. `
> > `No tests defined.`
> > Am I missing something?
> 
> Do you have `googletest` installed?

Just did, it works now, thanks!

**Comment by kelson42** [comment]
@shashwat1002 Have updated the README to put a word about gtest framework.
