### ISSUE TITLE
requires libzim 7.0.0 but newest version is 6.3.0

### ISSUE THREAD

**Issue by archenemies** [openzim/zim-tools#223]
I must be missing something? I just downloaded `libzim` and `zim-tools` and tried to build `zim-tools`; the changelog for `libzim` says 6.3.0 is the most recent version, but `zim-tools` complains that it wants 7.0.0.

Tried to back out to an earlier version with

    git checkout 7fe17cc075f13aca15f3665b0edfc5ccefd9dae1

but this results in a bunch of linker errors.

**Comment by kelson42** [comment]
Libzim 7.0.0 is still in developement. Use released versions of both zim-tools and libzim.

**Comment by archenemies** [comment]
Sorry I thought I was supposed to use `git clone` to obtain the latest versions. Where are the "released versions"?
