### ISSUE TITLE
zimdump produces invalid path in HTML-based redirect 

### ISSUE THREAD

**Issue by lidel** [openzim/zim-tools#224]
> - This is something I've found while working on https://github.com/ipfs/distributed-wikipedia-mirror/issues/60 
> - Not a hard blocker, will fix this for names without `/` in additional build step in https://github.com/ipfs/distributed-wikipedia-mirror/pull/77, but nice to fix it upstream in a way that works for all article names.

Assuming I understood this correctly, the HTML-based redirect created by `zimdump`  points at an invalid path.

### How to reproduce

`wikipedia_cr_all_maxi_2021-02.zim` is small enough to be a good demo:

```console
$ zimdump dump --dir=cr-tmp ./wikipedia_cr_all_maxi_2021-02.zim
$ cat cr-tmp/A/English_language
<!DOCTYPE html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="refresh" content="0;url=A/%E1%90%A7%E1%90%81%E1%92%A5%E1%94%A5%E1%91%8E%E1%91%AF%E1%94%92%E1%90%A4_%E1%90%8A%E1%94%A8%E1%92%A7%E1%90%A7%E1%90%83%E1%93%90" /><head><body></body></html>
```

So while in `A/{name1}` we are redirected to `A/{name2}`.

This looks like a bug, because the redirect is relative to `{name1}`, so it points at `A/A/{name2}` which does not exist.  

I was able to reproduce the same issue with 
- `wikipedia_cu_all_maxi_2021-02` – example: `A/Жена` effectively redirects to  `A/A/%D0%96%D1%94%D0%BD%D0%B0`
- `wikipedia_tr_all_maxi_2021-02`  – example:  `A/Fatih_Sultan_Mehmed` effectively redirects to `A/A/II._Mehmed`

#### Relative redirect

Ideally, a relative path would be used, without namespace prefix,  something like:

```diff
- <meta http-equiv="refresh" content="0;url=A/{name2}" /> 
+ <meta http-equiv="refresh" content="0;url={name2}" /> 
```

#### Open problem: subdirectories

The caveat is an edge case when a name with `/` is redirecting to something else.  Something like  `A/some/name`  needs to point at article one level up:

```diff
- <meta http-equiv="refresh" content="0;url=A/{name2}" /> 
+ <meta http-equiv="refresh" content="0;url=../{name2}" /> 
```

In case that  adds too much complexity to `zimdump` code,  we could  do that in JS.

If we replace `<meta>` tag with `<script>` then we are able to correctly redirect, no matter if name includes `/` or not. Something like: 

```html
<!doctype html>
<html lang="en">
<head>
<script>
  const from = 'na/me1'
  const to = 'name2'
  const prefix = window.location.pathname.split(from)[0]  
  window.location.replace(prefix + to)
</script>
<noscript>
  <meta http-equiv="refresh" content="0;url=name2" />  <!-- best-effort if no JS -->
</noscript>
</head>
</html>
```

@kelson42 lmk if there is a better way (or if I misunderstood how things work :))

**Comment by lidel** [comment]
@kelson42 fwiw I've worked around this in https://github.com/ipfs/distributed-wikipedia-mirror/pull/77/commits/11fe184edd597e5ff0d80edc52b01b9b77af1ebb by leveraging `find` `fgrep` and `sed`:

```sh
find ./wikipedia_tr_all_maxi_2021-02/A  -type f -size -800c -exec fgrep -l "0;url=A/" {} + -exec sed -i "s|0;url=A/|0;url=|" {} >> fixed_redirects.log +
```

Inspecting all articles takes too much time, so it looks for `0;url=A/` in files smaller than 800 bytes (so it only works on redirect ones, which are usually <500, while real articles are >1KB), and updates them in-place if needed.

**Comment by kelson42** [comment]
@veloman-yunkan may I ask you please to look at this ticket if you have the time? This is a pretty small one, but this impairs a bit the new Wikipedia snapshots release effort on IPFS we are running now.

**Comment by kelson42** [comment]
Two similar issues:
* https://github.com/openzim/mwoffliner/issues/164
* https://github.com/openzim/mwoffliner/issues/114

**Comment by veloman-yunkan** [comment]
@kelson42 OK, I will investigate it right away

**Comment by kelson42** [comment]
@veloman-yunkan Thank you! I looked yesterday to the code and the problem is clearly that there is no code *at all* to compute the relative path. The redirect targeted article fullpath URL is just put there. I believe we have a function somewhere (in `zimwriterfs`) to make this computation of a relative path given the current path and the target path. Probably could/should be reused.

**Comment by veloman-yunkan** [comment]
> I believe we have a function somewhere (in `zimwriterfs`?) to make this computation of a relative path given the current path and the target path. Probably could/should be reused.

I looked for such a function only in [`src/tools.h`](https://github.com/openzim/zim-tools/blob/65e38dd73ec23bf6ab1cbb05269e7f68be3e86e2/src/tools.h). Since it wasn't there I wrote my own implementation of it.
