### ISSUE TITLE
zimdump: proper handling of _exceptions

### ISSUE THREAD

**Issue by lidel** [openzim/zim-tools#226]
When it is not possible to dump article to `A/Foo`, zimdump outputs file to `_exceptions/A%2fFoo` instead.

This makes dump directory partially broken, as one can't expose it over HTTP due to errors described in https://github.com/ipfs/distributed-wikipedia-mirror/issues/61#issuecomment-784213485

I believe zimdump could handle exceptions like this more gracefully by implementing additional error handling, making the  output directory useful without the need for additional processing.

## Proposed exception handling

The idea here is to resolve conflict between File and Directory having the same name by leveraging the fact that the directory will load article from `index.html` when present.

### When exception is for name without `/` like  `A/Foo`

Only one article can exist under `A/Foo`, so if we are unable to write it, `A/Foo` is a directory created by dumping `A/Foo/Bar`.

Resolving exception for  `A/Foo`  is easy: 
- When exception occurs for a file without `/` in name, simply output the content of `Foo` article to `A/Foo/index.html`
   
### When exception is for name with `/` like  `A/Foo/Bar`

Dumping article with one or more `/` in name means a directory structure needs to be created.
In this case, an exception occurs when the target name is already taken by either a file or a directory, so we have two ways of resolving this.

In broad strokes, resolving exception for  `A/Foo/Bar` could work like this (each level needs to be checked, from left to right):

1. When exception occurs, check if `A/Foo` is a directory or a file (or missing, if checking deeper levels)
    - IF `A/Foo` is a directory, then nothing to fix at this level, repeat  (1) with next level (`A/Foo/Bar`)
    - IF `A/Foo` is a file, then we need to replace it with `A/File/index.html` to enable creation of subarticles
       - rename it to `A/Foo.tmp`
       - create directory `A/Foo`
       - move `A/Foo.tmp` to `A/Foo/index.html`
       - continue from (1) with next level (`A/Foo/Bar`)
     - IF `A/Foo` is missing, just write it

-----

I believe this should be fixed in `zimdump`, because right now a lot of articles fail to load due to being in `_exceptions` instead of the correct path. 

Hopefully this does not add too much overhead to `zimdump` – it for sure is way easier to fix it here than in userland scripts later, especially for English wikipedia with tens of milions of articles.

**Comment by kelson42** [comment]
@lidel Your proposal is far more complex than what exists, does simplify the reading under certain conditions and assumptions which are really specific. The system which has been created is a simple/generic one which is easy to understand and handle all use cases in the same manner (and article might fail to be written on the fs for many different reasons). Actually I don't understand exactly the problem to deal with it. Scanning the exceptions and urlencoding/decoding a few strings should not be a big deal?!

**Comment by lidel** [comment]
Absolutely, this can be fixed in userland too. 

Just wanted to see if this could be fixed in zimdump before we add any post-processing in [distributed-wikipedia-mirror](https://github.com/ipfs/distributed-wikipedia-mirror). This will make running each build slower, but should be doable.

@kelson42 just to be clear, so we don't duplicate efforts, this won't be implemented in zimdump, correct?

**Comment by mgautierfr** [comment]
This is not so easy. We could have those files in a zim archive :
- `foo/bar.html`
- `foo/index.html`
- `foo`
- `foo/`
- `foo///`
- `foo/bar/../index.html`

All of them can be a (mix of) file or a redirection.

**Comment by lidel** [comment]
Fair enough :) We will handle this in userland in https://github.com/ipfs/distributed-wikipedia-mirror/issues/80
