### ISSUE TITLE
zimdump does not dump redirects properly (empty files)

### ISSUE THREAD

**Issue by sharun-s** [openzim/zim-tools#23]
`zimdump -v -D ray wikipedia_en_ray_charles_2015-06.zim`

In the ray directory, to see all the files created of size 0
`find ray -size 0c `

Looks like this is not the intended use case, but I ran into issues when I tried to use zimdump+zimwriterfs to make some fixes and regenerate the ray charles zim https://github.com/openzim/zimwriterfs/issues/80. All the empty files turned into inode/x-empty direntries in the generated zim. Maybe in future, a process is possible where zimdump generates the "redirects tsv file" that zimwriterfs can consume to recreate redirect specific info.

**Comment by kelson42** [comment]
I think zimdump should probably create an HTML file with this header:
```
<meta http-equiv="refresh" content="0; url=http://example.com/" />
```
