### ISSUE TITLE
zimwriterfs does not handle poster attribute of video tag

### ISSUE THREAD

**Issue by tim-moody** [openzim/zim-tools#231]
Using latest release (Nov 17, 2020) on x86_64 ubuntu 20.10.

As viewed from a chrome browser,
Source tag is

`<video controls="" height="480" poster="../../../../../www.youtube.com/embed/deAt1q3jKBk.webp" src="../../../../../www.youtube.com/embed/deAt1q3jKBk.webm" video-format="244" width="853"></video>`

as returned from the zim it is

`<video controls="" height="480" poster="../../../../../www.youtube.com/embed/deAt1q3jKBk.webp" src="../../../../../../I/www.youtube.com/embed/deAt1q3jKBk.webm" video-format="244" width="853"></video>`

which renders the video but not the poster
whereas it should be

`<video controls="" height="480" poster="../../../../../../I/www.youtube.com/embed/deAt1q3jKBk.webp" src="../../../../../../I/www.youtube.com/embed/deAt1q3jKBk.webm" video-format="244" width="853"></video>`

which renders both

**Comment by kelson42** [comment]
We shoukd check first if the bug is still there with latest libzim/zimtools.

**Comment by tim-moody** [comment]
forgot to mention that this is with kiwix-serve 3.1.2

**Comment by mgautierfr** [comment]
> Quite sure this bug has disappeared as we don’t make any URL rewritting anymore.

Yes, the idea of removing the namespace is to have all resource at same level (at least not levels added by libzim) and so we don't need to rewrite the url.
On top of that, the compatibility layer in last libzim (not yet released) should probably handle this case (for old zim file).
