### ISSUE TITLE
Error "Exception: error 2 opening file" with zimDump

### ISSUE THREAD

**Issue by leanhdung1994** [openzim/zim-tools#232]
I'm using Docker on Windows 10 for [openzim/zim-tools](https://hub.docker.com/r/openzim/zim-tools). The zim file is `F:\zim\html wikipedia.zim`. The folder to contain html is `F:\zim\html`.
![image](https://user-images.githubusercontent.com/28704090/113622426-46453e00-965d-11eb-9b13-e52f3dce44ce.png)

I use `docker run -v /f:/zim -w /f:/zim -it openzim/zim-tools:latest zimdump dump --dir=/f:/zim/html wikipedia.zim`

But it returns an error `Exception: error 2 opening file "wikipedia.zim`. Could you please elaborate on this issue?

**Comment by kelson42** [comment]
I guess zimdump can not find the zim file because the path is wrong. Start a bash interactiveky and verify your command.

**Comment by leanhdung1994** [comment]
@kelson42 Can you elaborate on what `Start a bash interactively` means?

**Comment by kelson42** [comment]
https://www.google.com/search?q=docker%20start%20interactiveky%20bash&ie=utf-8&oe=utf-8&client=firefox-b-m

I close the ticket, this is problems with understanding how Docker works, not with zimdump.

**Comment by leanhdung1994** [comment]
@kelson42  First, I run `docker run -v /f:/zim -w /f:/zim -it openzim/zim-tools:latest sh`, then it shows

![image](https://user-images.githubusercontent.com/28704090/113628832-c8396500-9665-11eb-9ad6-89e1063c5bb6.png)

Then I run `zimdump dump --dir=/f:/zim/html wikipedia_en.zim` and it shows

![image](https://user-images.githubusercontent.com/28704090/113628893-e30bd980-9665-11eb-9aa3-3eaf01084951.png)

These are new to me. Can you instruct how I can go on to fix the error?
