### ISSUE TITLE
zimDump takes nearly 2 days to dump a 6GB zim file

### ISSUE THREAD

**Issue by leanhdung1994** [openzim/zim-tools#233]
Hello,

I'm using [openzim/zim-tools](https://hub.docker.com/r/openzim/zim-tools) inside Docker on Windows 10. I'm using module zimDump to dump `wiktionary_en_all_maxi_2021-03.zim` to html. The size of this zim file is 5.74GB. The dumping process has running for nearly 2 days and has not finished yet.

It's from [this discussion](https://github.com/openzim/zim-tools/issues/69#issuecomment-628621903) that

>The zimdump speed has been improved a lot (around 15x) but without adding multithreading.

Also in the same discussion, @lidel said that

> @kelson42 I can confirm, it is now within the same order of magnitude as the rust library, and can be used for practical purposes.
> 
> `wikipedia_tr_all_maxi_2020-04.zim` (4.4G):
> 
> * [dignifiedquire/zim](https://github.com/dignifiedquire/zim/): 1m13s
> * zimdump v1.1.1: 2m8s
> 
> Still slower, but that will change with multithreading.

Could you please shed some light on why my zimDump is very slow?

**Comment by kelson42** [comment]
Zimdump is not slow anymore. Maybe your computer is slow, you have a lot of content to dump, you use an old version... Or you are impatient. If you want more details, you can read the code and make a feature request if you have an idea how to make it quicker.

**Comment by lidel** [comment]
It is also possible you are using an older version. Grab the latest one from https://download.openzim.org/nightly/ and check if it improves anything.

**Comment by leanhdung1994** [comment]
@kelson42

The dumping is still running, so I'm not able to check the version right now. From docker,
![image](https://user-images.githubusercontent.com/28704090/115118121-1a518300-9fa2-11eb-86d1-2f298b27aab1.png)

It seems my version was updated 3 months ago and is **2.1.0**. My computer has 12 cores with 32GB RAM. The zim file is 5.74GB with 6.600.000 articles.

**Comment by leanhdung1994** [comment]
@lidel I've downloaded and unzip the files downloaded from your link. In the working directory, I have

```
root@7fe240b0d144:/zim# ls -R zim
zim:
libzim_linux-x86_64-2021-04-17         zim-tools_linux-x86_64-2021-04-17
libzim_linux-x86_64-2021-04-17.tar.gz  zim-tools_linux-x86_64-2021-04-17.tar.gz

zim/libzim_linux-x86_64-2021-04-17:
include  lib

zim/libzim_linux-x86_64-2021-04-17/include:
zim

zim/libzim_linux-x86_64-2021-04-17/include/zim:
archive.h  blob.h  entry.h  error.h  item.h  search.h  search_iterator.h  uuid.h  writer  zim.h  zim_config.h

zim/libzim_linux-x86_64-2021-04-17/include/zim/writer:
contentProvider.h  creator.h  item.h

zim/libzim_linux-x86_64-2021-04-17/lib:
x86_64-linux-gnu

zim/libzim_linux-x86_64-2021-04-17/lib/x86_64-linux-gnu:
libzim.so.7  libzim.so.7.0.0

zim/zim-tools_linux-x86_64-2021-04-17:
zimbench  zimcheck  zimdiff  zimdump  zimpatch  zimsearch  zimsplit  zimwriterfs
root@7fe240b0d144:/zim#
```

I tried to install zimdump but to no avail.

```
root@7fe240b0d144:/zim# xdg-open zimdump
xdg-open: file 'zimdump' does not exist
root@7fe240b0d144:/zim# ls -R zim
zim:
zimdump
```

I've only used Windows so far. Could you please inform me how to install zimdump?

**Comment by lidel** [comment]
Sadly I don't use Windows, but as a data point  my wikipedia builds were based on v2.2.0 (nightly), so you should try updated version.

**Comment by leanhdung1994** [comment]
> Try running with full or relative path ./zimdump. My wikipedia builds were based on v2.2.0 (nightly), so you should try updated version.

It seems `https://download.openzim.org/nightly/` is down
![image](https://user-images.githubusercontent.com/28704090/115140910-e75ace00-a039-11eb-97af-baf1230847b6.png)

Can you explain where to download the v2.2.0 (nightly)?

**Comment by leanhdung1994** [comment]
@lidel @kelson42  All compressed file from the link https://download.openzim.org/nightly/2021-04-19/ do not have the version prefix in their name. Can you explain where to download/update to version v2.2.0?

**Comment by lidel** [comment]
You can check the version with `zimdump --version`.
Simply pick the latest nightly.
