### ISSUE TITLE
zimrecreate should use libzim default encoding per default, so zstd

### ISSUE THREAD

**Issue by eroyee** [openzim/zim-tools#247]
A small thing perhaps but per https://github.com/kiwix/libkiwix/issues/554 it may be useful if _zimrecreate_ (and any other zim writing tools) could default to zstd compression and require a switch for lzma?

Presently lzma appears to be the default for _zimrecreate_ and it requires a switch for zstd, yet the latter algorithm appears to offer better compression (along with possibly faster extraction), and 'fixes' the error noted above.

**Comment by kelson42** [comment]
Actually, we don’t want to create ZIM files with lzma compression, therefore just removing the option.
