### ISSUE TITLE
Failure without reason

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-tools#249]
Running `zimcheck --empty --checksum --integrity --metadata --favicon --main --mime --details /data/beer_meta.zim` on http://tmp.kiwix.org/beer_meta.zim results in the following output.

```
[INFO] Checking zim file /data/beer_meta.zim
[INFO] Verifying ZIM-file structure integrity...
[INFO] Avoiding redundant checksum test (already performed by the integrity check).
[INFO] Searching for metadata entries...
[INFO] Searching for Favicon...
[INFO] Searching for main page...
[INFO] Verifying Articles' content...
[INFO] Overall Test Status: Fail
[INFO] Total time taken by zimcheck: 0 seconds.
```

As you can seem there is zero detail about what's wrong but the Overall status is `Fail` and the exit code is `1` which is of no use. Not sure whether there is a missing error detail or if it should succeed though.

**Comment by veloman-yunkan** [comment]
@rgaudin You are using quite an old version of zimcheck - the `--mime` option was dropped more than half a year ago (see 2337366c2389bd0a892c69786a53ff88389a64b6). A recent version reports a missing favicon:

```
[INFO] Checking zim file beer_meta.zim
[INFO] Verifying ZIM-archive structure integrity...
[INFO] Avoiding redundant checksum test (already performed by the integrity check).
[INFO] Searching for metadata entries...
[INFO] Searching for Favicon...
[INFO] Searching for main page...
[INFO] Verifying Articles' content...
[ERROR] Favicon:
  Favicon is missing
[INFO] Overall Test Status: Fail
[INFO] Total time taken by zimcheck: 0 seconds.
```

**Comment by rgaudin** [comment]
Ah sorry about that ; I am using the [latest released docker image](https://hub.docker.com/r/openzim/zim-tools/tags?page=1&ordering=last_updated) which is `2.1.0`.

**Comment by kelson42** [comment]
@rgaudin Can you please run the check with the cutting edge zimcheck?

**Comment by rgaudin** [comment]
Hum… I surely get the same results as @veloman-yunkan when testing with the latest nightly.

Two concerns arise though:
- zimcheck is integrated into zimfarm. It's the foundation of the to-come CMS. If the latest release is considered obsolete, maybe it's time to release 😀 Kidding, I know why it' not. @kelson42 we need a docker image for zimfarm so should we publish an `openzim/zim-tools:nightly` docker image that's built every day with the latest nightly? I can send a PR for that.
- With [this new zim](http://tmp.kiwix.org/beer_meta_stackexchange_com_2021-07.zim) I am still getting the Favicon error although it does have an (actually 2) Illustration. Should I open a ticket for that?
