### ISSUE TITLE
Questions about release 3.0.0

### ISSUE THREAD

**Issue by tim-moody** [openzim/zim-tools#268]
It seems 3.0.0 was released 25 days ago with some more commits 18 days ago. One of the features is given as

- Adapt zim tools to new libzim api (@MGautier @veloman-yunkan @maneesh)

But it is not clear what is 'new libzim api'. Is this libzim 7.0?

Also http://download.kiwix.org/release/kiwix-tools/ has release 3.1.2 from 15 months ago. What is the relationship between that 3.1.2 and this 3.0.0?

Where is the best place to obtain binaries for the latest zim-tools, nightly? Is libzim linked in or must it be obtained separately?

**Comment by mgautierfr** [comment]
> But it is not clear what is 'new libzim api'. Is this libzim 7.0?

Yes. There is no specific commits for this "feature" but we zim-tools use libzim 7.0 and so we keep the code in sync with it.

> Also http://download.kiwix.org/release/kiwix-tools has release 3.1.2 from 15 months ago. What is the relationship between that 3.1.2 and this 3.0.0?

kiwix-tools and zim-tools are two different projects 🙂 

> Where is the best place to obtain binaries for the latest zim-tools, nightly? Is libzim linked in or must it be obtained separately?

You can get the last release at http://download.openzim.org/release/zim-tools/ or the nightlies here : http://download.openzim.org/nightly/

Binaries are statically linked so no need to get libzim separately.
