### ISSUE TITLE
dump to zim, xml2zim

### ISSUE THREAD

**Issue by erickeller** [openzim/zim-tools#269]
the following page create once or twice a month a complete dump of wikipedia, 
https://dumps.wikimedia.org/backup-index.html

I browsed a bit the documentation about openzim yet did not find any response.
zim-tools contain some `zimwritefs` which would take some local html site, yet the official wikipedia dumps are single plain xml files.

 to my understanding the mwoffliner project https://github.com/openzim/mwoffliner does download every single article from a base wikimedia wiki. This is how one generates the current zim file hosted on: https://wiki.kiwix.org/wiki/Special:MyLanguage/Content_in_all_languages using the https://farm.openzim.org/ worker farm.

I assume being able to reuse already populated wikipedia dumps would safe bandwidth / requests and simplify automation pipelines for wikimedia.

What is the rational something like xml2zim has not been considered so far?

**Comment by kelson42** [comment]
@erickeller You have understood everything properly. AFAIK, the dumps have wiki code and what we need in the ZIM files is HTML. So it is not possible to use `zimwriterfs` straight.

**Comment by erickeller** [comment]
ok including another tool e.g. pandoc, to convert the wiki markdown to html and then use zimwritefs is also not something to consider/investigate?

**Comment by kelson42** [comment]
@erickeller You will need a wiki engine, ideally Mediawiki itself. This needs a lot of computing power. This is what we were doing 10 years ago. The mwoffliner is a lot easier to run.
