### ISSUE TITLE
arquivo zim

### ISSUE THREAD

**Issue by asbsbv** [openzim/zim-tools#270]
gostaria da ajuda dos membros para poder migrar os dados de um programa na linguagem ZIM, para outra que possibilite a vinculação destes dados com outra plataforma, se puderem me ajudar agradeço pois não tenho conhecimento na linguagem .zim , e gostaria de ajudar uma ONG que possui um programa de banco de dados que usa esta linguagem e que aqui no brasil não se consegue informações como migrar e
[INSTALA2.txt](https://github.com/openzim/zim-tools/files/7728761/INSTALA2.txt)
ste banco de dados para outro aplicativo

**Comment by kelson42** [comment]
Bug reports have to be written in Eng,ish to be understood by everybody.
