### ISSUE TITLE
Segmentation fault with zimwriterfs

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#289]
From kiwix-tools created by [ru2saig](https://github.com/ru2saig): kiwix/kiwix-tools#537  

I was trying to create a zim file from a not so large directory, but zimwriterfs fails with a segmentation fault. I have made an log  from strace (attached at the end). Also do ya'll need any more logs? What should I try? What other information would ya'll like? 

Running Debian GNU/Linux bookworm/sid

Using kiwix-tools from the repositories
`apt show kiwix-tools` shows version at 3.2.0-2

My kiwix-tools version for zimeriterfs: 
```zim-tools 3.1.0

libzim 7.2.0
+ libzstd 1.4.8
+ liblzma 5.2.5
+ libxapian 1.4.18
+ libicu 67.1.0
```
Used 
``` zimwriterfs --welcome index.html --illustration=icon.png --language=en --title=TheMathPage --description="TheMathPage by Lawrence Spector" --creator="Lawrence Spector" --publisher="Kiwix" ./themathpage.com themathpage.zim```

The log generated by strace:
[zimwriterfs.log](https://github.com/kiwix/kiwix-tools/files/8041783/zimwriterfs.log)

**Comment by kelson42** [comment]
@ru2saig Thank you for your bug report. Any chance we could have somehow the source tarball (the documents you want to put in the ZIM) so we can reproduce the bug? Even privatly?

**Comment by ru2saig** [comment]
Yes I can send the files, but where to? I would like to send them privately since I'm not sure if I have the copyrights!

**Comment by kelson42** [comment]
@ru2saig Please send them to me at kelson_@_kiwix.org

**Comment by ru2saig** [comment]
I am unable to send the email to that address. It is saying that it does not exist. (using gmail)

**Comment by kelson42** [comment]
@ru2saig yes, without underscores, just a way to avoid the email address being gathered by a bot.

**Comment by ru2saig** [comment]
Sent. Let me know if you need anything else.

**Comment by kelson42** [comment]
@veloman-yunkan I have investigated a bit and it seems something fundamentaly wrong go there around the compressions which is not properly set.

First `zim::Compression::Zstd` should be the default at libzim level, and it seems it is not.

Then, problem seems to appear with libzim7.2.0 as well, so this is a regression which we don't have detected... and I really wonder why (because is it a basic use case of `zimwriterfs`)

Then, I set the problem compression config in Zimwriterfs at the creator creation, but same error! So I'm pretty lost.

Hope you can help there.

**Comment by ru2saig** [comment]
```
 $ zimwriterfs --welcome index.html --illustration=icon.png --language=en --title=TheMathPage --description="TheMathPage by Lawrence Spector" --creator="Lawrence
Spector" --publisher="Kiwix" ./themathpage.com themathpage.zim
Segmentation fault
```

This is what I get when I run it on my system.

**Comment by veloman-yunkan** [comment]
I was able to reproduce the issue with another set of data. The problem is that ZIM creation is not exception safe. When an exception is thrown after `zim::Creator::startZimCreation()` has been executed, `zim::Creator` is destroyed without `zim::Creator::finshZimCreation()` having been called. This scenario is not anticipated in the current implementation of `libzim`. The result is a memory corruption with any possible kind of subsequent undefined behaviour (in this case showing up as a false "invalid compression flag" error).

On my test case the exception was triggered by an invalid redirect but that is secondary.

**Comment by kelson42** [comment]
@veloman-yunkan Do you talk about https://github.com/openzim/libzim/issues/475? Or is that something else?

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Do you talk about [openzim/libzim#475](https://github.com/openzim/libzim/issues/475)? Or is that something else?

@kelson42 I didn't remember about that ticket. But on my test case the problem was of a different kind (no callbacks from `zim::Creator` were involved).

**Comment by kelson42** [comment]
@ru2saig Problem should be fixed, but we still work on a solution to secure you don't have to use `ulimit` to allow more than 1024 files open at the same time.
