### ISSUE TITLE
Issue using zimdump to export with .html extension

### ISSUE THREAD

**Issue by Dalton-Overlin** [openzim/zim-tools#304]
Hi, using the latest version of zimdump on Ubuntu it exports file data without any file extension name. For example, the exported files that contain html, do not have a file extension name. Is there a way I can specify that zimdump exports the folders containing html to have the file extension of       .html

If you could offer any solutions on this I would appreciate it very much.

**Comment by kelson42** [comment]
Yes, this is normal. The filenames are like in the ZIM file. If we change them, the we would have to rewrite the links in the HTML as well. What we don't want to do. What is the problem of having files without extensions?

**Comment by Dalton-Overlin** [comment]
I will be storing these files on a personal server after extraction, but they will have been modified. Most browsers only display the html if the file loaded has the .html extension. Would you happen to know of a program that could rename the files and rewrite the html contents to reflect the changes to the file names?

**Comment by kelson42** [comment]
@Dalton-Overlin I don't know such a software. But, may I ask why you want to do so instead of just using the ZIM file?

**Comment by Dalton-Overlin** [comment]
I need to modify the HTML files programmatically. But thank you for taking the time to reply to me, I appreciate it.

**Comment by kelson42** [comment]
@Dalton-Overlin Then you better fix the problem at the source, in MWoffliner.
