### ISSUE TITLE
Core dump checking latest stackoverflow

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-tools#305]
`time zimcheck -A /data/download/zim/stack_exchange/stackoverflow.com_en_all_2022-05.zim`

```
[INFO] Checking zim file /data/download/zim/stack_exchange/stackoverflow.com_en_all_2022-05.zim
[INFO] Zimcheck version is 3.1.1
[INFO] Verifying ZIM-archive structure integrity...
[INFO] Checking zim file /data/download/zim/stack_exchange/stackoverflow.com_en_all_2022-05.zim
[INFO] Zimcheck version is 3.1.1
[INFO] Verifying ZIM-archive structure integrity...
[INFO] Avoiding redundant checksum test (already performed by the integrity check).
[INFO] Searching for metadata entries...
[INFO] Searching for Favicon...
[INFO] Searching for main page...
[INFO] Verifying Articles' content...
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace_aux
Aborted (core dumped)

real    35m43.516s
user    31m19.384s
sys     5m24.876s
```

```
zimcheck --version
zim-tools 3.1.1

libzim 7.2.2
+ libzstd 1.5.2
+ liblzma 5.2.4
+ libxapian 1.4.18
+ libicu 58.2.0
```

**Comment by rgaudin** [comment]
@kelson42 no I don't but it looks like the log is giving a hint about what's happening and where. Hopefully that's enough…

**Comment by veloman-yunkan** [comment]
> @kelson42 no I don't but it looks like the log is giving a hint about what's happening and where. Hopefully that's enough…

Unfortunately, the information in the log only tells about an out-of-bounds access during a mutating operation on a string object, which is absolutely not enough to pinpoint the root cause.

@kelson42 Can I debug this remotely?

**Comment by veloman-yunkan** [comment]
@kelson42 I feel that you missed my feedback. Is there a way for me to debug this crash remotely (without having to download the ZIM)?

**Comment by kelson42** [comment]
@veloman-yunkan I don't have forgotten you. But the we have neither a reproduction case with a smaller ZIM file nor a dedicated online env. we could give you access to.

Usually and so far, most of us (devs) have access to private online linux servers we do use as playground or debug environnements. This kind of need has been solved that way.

@rgaudin I wonder if we could create temporary environnements in our new K8s env easily and more or less on demand for tvat purpose? If "yes", would we have the necessary hardware without putting at risk to make any critical service potentially unstable?

**Comment by rgaudin** [comment]
@veloman-yunkan @kelson42 I've setup a debian container that we can use for this purpose. I'll contact you on Slack with details

**Comment by veloman-yunkan** [comment]
There is a bad link in the article `users/241039/oleh-prypin` (entry idx=58950210) in the ZIM file:

```html
<a href="//meta.stackoverflow.com/../../users/17034/hans-passant?tab=answers&amp;sort=votes#user-tab-answers">
```

The corresponding link at the current version of https://stackoverflow.com/users/241039/oleh-prypin is

```html
<a href="//meta.stackoverflow.com/users/17034/hans-passant?tab=answers&amp;sort=votes#user-tab-answers">
```

The scraper added unjustified "../.." in an absolute URL belonging to a different domain.

Of course zimcheck shouldn't crash because of it and I will fix that. But now you have early indication to the bug in the scraper.

**Comment by rgaudin** [comment]
Given that this link is correct (although including superfluous relative jumps), I'd say no. What kind of check do you have in mind?

**Comment by veloman-yunkan** [comment]
@rgaudin The link is incorrect - you cannot go up from the top level

**Comment by rgaudin** [comment]
No it's not, test for yourself. Above-root resolved segments are to start from the root so you'll see that the first URL above is equivalent to the second one.

**Comment by veloman-yunkan** [comment]
> Above-root resolved segments are to start from the root

@rgaudin With such a rule - yes, the two URLs are equivalent. But is such handling of above-root standardized somewhere? Can you point to a spec?

**Comment by rgaudin** [comment]
Maybe https://www.rfc-editor.org/rfc/rfc3986#section-3.3

> The path segments "." and "..", also known as dot-segments, are
   defined for relative reference within the path name hierarchy.  They
   are intended for use at the beginning of a relative-path reference
   ([Section 4.2](https://www.rfc-editor.org/rfc/rfc3986#section-4.2)) to indicate relative position within the hierarchical
   tree of names.  This is similar to their role within some operating
   systems' file directory structures to indicate the current directory
   and parent directory, respectively.  However, unlike in a file
   system, these dot-segments are only interpreted within the URI path
   hierarchy and are removed as part of the resolution process ([Section](https://www.rfc-editor.org/rfc/rfc3986#section-5.2)
   [5.2](https://www.rfc-editor.org/rfc/rfc3986#section-5.2)).

**Comment by veloman-yunkan** [comment]
Thanks. The section [5.2 Relative Resolution](https://www.rfc-editor.org/rfc/rfc3986#section-5.2) of that RFC and its subsection [5.2.4 Remove Dot Segments](https://www.rfc-editor.org/rfc/rfc3986#section-5.2.4) indeed maintain that going above root is a no-op. 

But then we probably better remove the out-of-bounds check for internal links?

https://github.com/openzim/zim-tools/blob/92fc9c7b28ed9381e15ff76fd7b16f5d7441679f/src/zimcheck/checks.cpp#L437-L441

**Comment by rgaudin** [comment]
I'm not sure. Internal, we have control over and we want to check that we won't end up with broken links. Given absolute URI are prohibited because scraper can't know at which path (if any) a resource will be served, it's safe to assume that out of bound should be prohibited for internal links as well ?

**Comment by veloman-yunkan** [comment]
> Given absolute URI are prohibited because scraper can't know at which path (if any) a resource will be served, it's safe to assume that out of bound should be prohibited for internal links as well?

Good point!
