### ISSUE TITLE
Limit task queue size in zimcheck

### ISSUE THREAD

**Issue by veloman-yunkan** [openzim/zim-tools#308]
Before #194 zimchecks processed entries one after another. Support for multi-threading relies on a task queue where every entry from the ZIM file is treated as a separate task. The main thread populates the queue and worker threads process tasks from it (this scheme is used also when zimcheck is run in "single-threaded" mode which means that there is a single worker thread).

The current problem is that there is no limit on the task queue size, and the main thread keeps filling it until all entries have been pushed into the queue. For large ZIM files this results in a lot of memory being consumed by the task queue. For example, on a machine with 8GB of RAM `zimcheck --url_internal --url_external ` fails to handle [`stackoverflow.com_en_all_2022-05.zim`](http://download.kiwix.org/zim/stack_exchange/stackoverflow.com_en_all_2022-05.zim) (which has more than 64M entries).

**Comment by kelson42** [comment]
@veloman-yunkan Sounds indeed really dangerous. Any queue system should have a loopback system to slow down the pushing when the pulling is too slow.
