### ISSUE TITLE
Easy way to change metadata of zim file (im zimrecreate)?

### ISSUE THREAD

**Issue by tim78245** [openzim/zim-tools#317]
I made some zim files about a year ago but didn't realize "en" was incorrect for the language.

Is there a way to easily change it to "eng" (what I presume is correct?)

**Comment by kelson42** [comment]
There is no way to do that for the moment. It might be a pretty easy option to `zìmrecreate` to implement.

**Comment by FledgeXu** [comment]
Also it would be nice if zim-tools had tools to display the metadata of zim files.

**Comment by kelson42** [comment]
To me we should decided if zimrecreate shoukd be tweaked or if a new toold shoukd be created, see #74

**Comment by kelson42** [comment]
Clising as basically a duplicate.
