### ISSUE TITLE
zimwriterfs: warn if link doesn't exist

### ISSUE THREAD

**Issue by tim78245** [openzim/zim-tools#324]
Example, if I have an html file that has

```
<img src="notexist.png">
```

And notexist.png does not exist, zimwriterfs will not tell me.

However, it would be useful to know beforehand if my zim file is missing any resources.

Alternatively, if someone has something that would achieve the same result (some sort of wget spider hack perhaps?), I'd be happy knowing how.

**Comment by mgautierfr** [comment]
> Alternatively, if someone has something that would achieve the same result (some sort of wget spider hack perhaps?), I'd be happy knowing how.

zimcheck does this.

**Comment by kelson42** [comment]
@tim78245 The tooling you need is not strictly related to the ZIM format. For the ZIM we have `zimcheck`. For your raw input dump, you might find other tools. I have https://www.getsiteinspector.com/ in mind, but that might be slightly overkill.
