### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by clinpp** [openzim/zim-tools#341]
**I am having some compilation issues when compiling zim-tools, and the error messages are as follows:**

zim-tools % meson . build                                                         
The Meson build system
Version: 1.0.1
Source dir: /Users/xxxx/Documents/kiwix/zim-tools
Build dir: /Users/xxxx/Documents/kiwix/zim-tools/build
Build type: native build
Project name: zim-tools
Project version: 3.1.3
C compiler for the host machine: cc (clang 13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2.5)")
C linker for the host machine: cc ld64 764
C++ compiler for the host machine: c++ (clang 13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2.5)")
C++ linker for the host machine: c++ ld64 764
Host machine cpu family: aarch64
Host machine cpu: aarch64
meson.build:6: WARNING: Consider using the built-in werror option instead of using "-Werror".
meson.build:6: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
Found CMake: /opt/homebrew/bin/cmake (3.26.2)
Run-time dependency libzim found: NO (tried framework and cmake)

meson.build:19:0: ERROR: Dependency lookup for libzim with method 'pkgconfig' failed: Could not generate cargs for libzim:
Package icu-i18n was not found in the pkg-config search path.
Perhaps you should add the directory containing `icu-i18n.pc'
to the PKG_CONFIG_PATH environment variable
Package 'icu-i18n', required by 'libzim', not found

**I am using a Mac1 chip, and I have tried both`brew install libzim`, `pip install libzim`, but they did not work as I expected. Is it because the configuration path of my libzim is incorrect that caused the error?**

**Comment by kelson42** [comment]
> Run-time dependency libzim found: NO (tried framework and cmake)

The error is clear, the libzim is not found, either not installed or not detectable.
