### ISSUE TITLE
Fails to build on PPA for arm64

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#345]
Not sure if this is related to the recent merge of #339, but our PPA fails now to build on all Ubuntu versions for arm64, see for example:
https://launchpadlibrarian.net/663267720/buildlog_ubuntu-jammy-arm64.zim-tools_3.1.3+git202304261442.54ba91f~jammy_BUILDING.txt.gz

**Comment by veloman-yunkan** [comment]
I cannot reproduce this failure using my own build of zimcheck on raspberry pi.

**Comment by veloman-yunkan** [comment]
One major difference in my build procedure is that I compiled libzim myself instead of installing it from http://ppa.launchpadcontent.net/kiwixteam/dev/ubuntu. I will now try the other way.

**Comment by veloman-yunkan** [comment]
Same outcome - no crash.

**Comment by kelson42** [comment]
Lets see if 8.2.0 fails as well then.

**Comment by kelson42** [comment]
So, problem is still there with `8.2.0`, see https://launchpad.net/~kiwixteam/+archive/ubuntu/dev/+build/26166159/+files/buildlog_ubuntu-jammy-arm64.zim-tools_3.2.0+git202305191216.3c48df6~jammy_BUILDING.txt.gz

Looks really like we have something which is broken here.
