### ISSUE TITLE
Zimwriterfs Can't Find Welcome Page

### ISSUE THREAD

**Issue by PlumbusFleeb** [openzim/zim-tools#389]
**Background**: `index.html` is located in `./git-scm.com/docs` along with the rest of the files. I am trying to .zim only that /docs directory.

`:~/Downloads$ zimwriterfs --version`
`zim-tools 3.3.0`
`+ libmagic 544`

`libzim 8.1.1`
`+ libzstd 1.5.4`
`+ liblzma 5.4.1`
`+ libxapian 1.4.22`
`+ libicu 72.1.0`

I attempt to create the zim file using the following:

`:~/Downloads$ sudo zimwriterfs -w index.html -I zim-favicon.png -l eng -t git_docs -d Rip of the git application documentation -c Me -p EoW -v ./git-scm.com/docs ./git_doc.zim `

**The error I get**:

`zimwriterfs: unable to find welcome page at 'of/index.html'. --welcome path/value must be relative to HTML_DIRECTORY.`

I've tried many times to reword the command in various ways to get zimwriterfs to find the homepage. If I haven't given enough information, I apologize. I'm still relatively new and this is my first time ever reaching out online for help. I am completely lost on this one and would appreciate any help.

**Comment by veloman-yunkan** [comment]
Your argument to the `-d` option contains spaces, so it must be quoted

```
zimwriterfs ... -d "Rip of the git application documentation" ...
```

BTW, why do you run `zimwriterfs` via sudo?

**Comment by PlumbusFleeb** [comment]
Thank you for getting back with me. Regarding sudo, I was having issues with folders becoming randomly owned by root. I fixed that issue and never removed it from the command.

I pu the -d option around quotes and still have the same issue.

**Comment by PlumbusFleeb** [comment]
Sorry, I am dumb. I wasnt cd'd into the proper folder.

Here is the new command:

 `~/Downloads$ zimwriterfs -w index.html -I logo@2x.png -l eng -t git_docs -d "Rip of the git application documentation" -c Me -p EoW -v ./git-scm.com/docs ./git_doc.zim `

Here is the new error:

`Metadata doesn't meet the following requirements:
    Name must contain at least 1 characters`

**Comment by PlumbusFleeb** [comment]
Dumb again...

I figured out that I had missing mandatory arguments. All is good now. Thank you!!!
