### ISSUE TITLE
zimdump -error in specifying namespace

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#4]
Description:
In zimdump, when the '-n ns' arg is given, the results are from all namespaces, not just the specified namespace.

However, when the -f arg is given along with it, it works.

I'm not sure whether this is the way the developers intended it to be, so I need some confirmation before trying a fix.

For example,

zimdump -n I -l wikipedia.zim

and

zimdump -l wikipedia.zim

gives the same result.

-----------
First reported here https://phabricator.wikimedia.org/T50438

**Comment by kelson42** [comment]
Seems also to be a bug too me, at least with "-l"...

@mgautierfr ... as you are working currently on that piece of code you could please confirm/fix?

**Comment by mgautierfr** [comment]
This is intended by the developers. So not a bug.

However, the api of `zimdump` is a bit surprising and deserve some explanation : 

`zimdump` executes a series of operation always in the same order and if the corresponding option are given :
- Printing "global" information about a zim (`-F`, `-N`)
- Locating an article using `-o` or  (`-n` and `-f` and `-t`) or `-u`. If none of those options are given, the located article is the first one.
- Potentially dump all articles from the located article to the last one into the given directory (`-D`)
- Print information: the data (`-d`) or the page (`-p`) or the article**s** from located article to the last one (`-l` or `-L`) or the article information (`-i`)
- And then verify the checsum (if `-C` is given)

The `-n` argument (as `-t`) is only used if `-f` is given.

**Comment by kelson42** [comment]
@mgautierfr This behaviour is quite odd... This should be documented in the usage()... at least.

**Comment by kelson42** [comment]
@MiguelRocha I believe this ticket should be automatically fixed by your work these days.
