### ISSUE TITLE
3.4.1 zimwriterfs - keep getting Illustration_48x48@1 doesn't match regex: ^\x89PNG\x0d\x0a\x1a\x0a

### ISSUE THREAD

**Issue by kashortiexda** [openzim/zim-tools#405]
on 3.4.1 zimwriterfs - keep getting Illustration_48x48@1 doesn't match regex: ^\x89PNG\x0d\x0a\x1a\x0a no matter what 48x48.png I use as favicon.png

**Comment by kelson42** [comment]
@kashortiexda Your favicon is not a PNG file

**Comment by kelson42** [comment]
The format of the picture file you have given as illustration is not https://en.wikipedia.org/wiki/PNG
