### ISSUE TITLE
zimdump cannot handle retrieval by url with common "-" namespace

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#5]
Author: braddock

Description:
zimdump does not reliably find articles via url if the namespace is "-", as is common. The argument parser seems to get mangled and the result is not predictable.

For example:
zimdump -i -u -/MediaWiki~KiwixOffline_0.css wikipedia_en_all_nopic_01_2012.zim

First reported here: https://phabricator.wikimedia.org/T50383

**Comment by kelson42** [comment]
@mgautierfr Could you please have a look to this as you are currently working on that piece of code?

**Comment by mgautierfr** [comment]
It seems there is no bug here, the given url is correctly parsed by the argument parser.

However, the libzim `find` function used by `zimdump` to locate the article given an url is the function use to "search" a article in the zim file. If the url doesnt't exist, it return the closer article.

So, if the request article is not present in the zim, the content printed is the content of a different article,
that could be pretty surprising. 

I've already face similar problem. I've naivly try to change it and break https://github.com/kiwix/kiwix-android/issues/84 . I had to re-add this behaviour here https://github.com/openzim/libzim/commit/7883cb8b54eee05d824f5f3b57e2091e56c1461e
