### ISSUE TITLE
zimdump should unescape paths before creating assets

### ISSUE THREAD

**Issue by lidel** [openzim/zim-tools#68]
> Issue extracted from https://github.com/ipfs/distributed-wikipedia-mirror/issues/66

It seems that filenames in assets directories (`-` and `I`) are not unescaped (`%2f` should be `/`) and filenames end up at the top level directory with invalid names:

```console
$ zimdump -V
1.0.5
$ zimdump -D ray wikipedia_en_ray_charles_maxi_2019-10.zim
$ tree ray
ray
├── -
│   ├── favicon
│   ├── j%2fjs_modules%2farticle_list_home.js
│   ├── j%2fjs_modules%2fdetails_polyfill.js
...
│   ├── s%2fcog-sprite.svg
│   ├── s%2fcss_modules%2fcontent.parsoid.css
...
├── I
│   ├── m%2fAankomst_Ray_Charles_(kop)_op_Schiphol,_Bestanddeelnr_921-7410.jpg
│   ├── m%2fAmbox_important.svg.png
│   ├── m%2fA_Portrait_of_Ray.jpg
...
```

I believe `s%2fcss_modules%2fcontent.parsoid.css` should be `s/css_modules/content.parsoid.css`, because that is what HTML in `A/*` articles expects:

```html
  <link href="../-/s/css_modules/style.css" rel="stylesheet" type="text/css">
...
  <script src="../-/j/js_modules/script.js"></script>
```

**Comment by orionseye** [comment]
Unbelievable this has not being implemented, i was hit by a dinosaur looking at the extracted results :)
This is must have..please?
