### ISSUE TITLE
Wrong timekeeping in zimbench

### ISSUE THREAD

**Issue by veloman-yunkan** [openzim/zim-tools#77]
In zimbench, time calculation from seconds+nanoseconds to milliseconds is carried out assuming that 1 ms == 1000 ns:

- https://github.com/openzim/zim-tools/blob/e2cb9cb9be0fe9739581d31f86613f7df17eea1a/src/zimbench.cpp#L153
- https://github.com/openzim/zim-tools/blob/e2cb9cb9be0fe9739581d31f86613f7df17eea1a/src/zimbench.cpp#L166
- https://github.com/openzim/zim-tools/blob/e2cb9cb9be0fe9739581d31f86613f7df17eea1a/src/zimbench.cpp#L178
- https://github.com/openzim/zim-tools/blob/e2cb9cb9be0fe9739581d31f86613f7df17eea1a/src/zimbench.cpp#L188

This is off by a factor of 1000x (actually 1ms == 1,000,000 ns). As a result one may observe even negative duration values (caused by integer overflow).

**Comment by data-man** [comment]
Should be rewritten using `std::chrono::steady_clock::now`.
