### ISSUE TITLE
Zimcheck crach scenario

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#91]
$ zimcheck edutechwiki_fr_all_maxi_2020-05.zim 
[INFO] Checking zim file edutechwiki_fr_all_maxi_2020-05.zim
[INFO] Verifying Internal Checksum.. 
  [INFO] Internal checksum found correct
[INFO] Searching for metadata entries..
[INFO] Searching for Favicon..
[INFO] Searching for main page..
[INFO] Verifying Articles' content.. 
basic_string::_M_replace_aux
$ echo $?
2
```

**Comment by MiguelRocha** [comment]
_**pre analysis:**_
It seems to be an issue with a validation of title size at direct.cpp:
```
    if (current.v + title_size >= buffer->size().v) {
      throw(InvalidSize());
    }
```
some hints about the dirent in question:
- ns = A
- url = "Apprentissage_collaboratif/Les_interactions_dans_l'apprentissage_collaboratif/Grille_(remplacez_par_qc.)Apprentissage_collaboratif/Les_interactions_dans_l'apprentissage_collaboratif_-_Katrine_Briguet"
- redirect = true

**Comment by mgautierfr** [comment]
Hum, it is surprising. This should be catched here : https://github.com/openzim/libzim/blob/master/src/fileimpl.cpp#L315-L345

**Comment by kelson42** [comment]
@mgautierfr @MiguelRocha Thank you to both of you for your quick feedback. I was not too worry of this bug because this is in `zimcheck` so impact limited and not cutting edge code... but of course, if the bug has its root in libzim then priority is of course higher!

**Comment by mgautierfr** [comment]
I suppose we have the same crash if we try to access the article in kiwix-serve.

**Comment by kelson42** [comment]
> I suppose we have the same crash if we try to access the article in kiwix-serve.

Seems to work fine:
```
 curl --dump-header /tmp/headers "http://library.kiwix.org/edutechwiki_fr_all_maxi_2020-05/A/Apprentissage_collaboratif/Les_interactions_dans_l'apprentissage_collaboratif/Grille_(remplacez_par_qc.)Apprentissage_collaboratif/Les_interactions_dans_l'apprentissage_collaboratif_-_Katrine_Briguet" && cat /tmp/headers
HTTP/1.1 302 Found
Server: nginx/1.17.5
Date: Mon, 04 May 2020 16:46:14 GMT
Content-Length: 0
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate
Access-Control-Allow-Origin: *
Location: /edutechwiki_fr_all_maxi_2020-05/A/Apprentissage_collaboratif/Les_interactions_dans_l'apprentissage_collaboratif_-_Katrine_Briguet

```

**Comment by kelson42** [comment]
After discussing with @mgautierfr and @MiguelRocha it seems to be a bug in the libzim.

**Comment by mgautierfr** [comment]
It seems it is not a problem relative to `InvalidSize` exception.

The crash is in zim-tools (https://github.com/openzim/zim-tools/blob/master/src/zimcheck.cpp#L211) where we try to normalize `../../../../file.js` using the base url `A`).
