### ISSUE TITLE
Move zimwriterfs to zim-tools repo

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#92]
This would simplify a few things.

**Comment by kelson42** [comment]
@MiguelRocha @mgautierfr @rgaudin Comments?

**Comment by MiguelRocha** [comment]
Makes sense in my opinion.

**Comment by data-man** [comment]
Why are there even a few apps?
Why not one app (zim) with subcommands (create, test, etc.)?

**Comment by mgautierfr** [comment]
Yes we could move zimwriterfs in zim-tools.

I have no particular opinion about merging the tools in one.

**Comment by kelson42** [comment]
> Why are there even a few apps?
> Why not one app (zim) with subcommands (create, test, etc.)?

Not sure about that. This is an idea. But definitive an other topic.

**Comment by asashnov** [comment]
What to do with **zimwriterfs-in-docker** script then?
https://github.com/openzim/zimwriterfs/blob/master/contrib/zimwriterfs-in-docker

**Comment by rgaudin** [comment]
This can go away now that we have (almost) a libzim bin for macos. we’ll also distribute macos zimwriterfs

**Comment by kelson42** [comment]
@asashnov but keep the `docker` directory please, I will update the automatic build in hub.docker.com.

**Comment by asashnov** [comment]
An idea: we can distribute zim-tools as an AppImage package on Linux, so it can be run like:
```
./Zim-Tools.AppImage help   - will list all available tools
./Zim-Tools.AppImage zimdump --help
./Zim-Tools.AppImage zimwriterfs --help
```
It will consume less disk space then statically linked binaries, as dynamic libraries will be put inside of AppImage archive once.
