### ISSUE TITLE
Issue using zimdump to extract zim file.

### ISSUE THREAD

**Issue by Dalton-Overlin** [openzim/zim-tools#97]
Hello, I am using the latest release of zim-tools on Ubuntu 18.04 LTS x64 bit with 7.7 gigs of ram and an i7 processor.

The issue is I am trying to dump the contents of a zim file I downloaded from kiwix, from this link: http://download.kiwix.org/zim/wikipedia_en_all_maxi.zim

I used this command below to call zimdump to extract the contents to a folder. 

zimdump "/media/nichola/26C65A13C659E419/Users/Styles/Downloads/Zim-P/wikipedia_en_all_maxi_2018-10 (1).zim" -D "/media/nichola/26C65A13C659E419/Users/Styles/Downloads/Zim-P/Dump"

But while that command was running zimdump produced this message below and stopped running. My question is what should I do to overcome this issue? Is this a bug with zimdump, an issue with the zim file, or something else? Any help on this issue would be greatly appreciated. 

unknown mime type code 65535

**Comment by kelson42** [comment]
@MiguelRocha Not sure if this is a bug in the ZIM file (quite old now) or in the libzim/zimdump. Would you be able to enlight us?

**Comment by mgautierfr** [comment]
A mimetype 65535 (0xffff) is a redirect article.
I don't know what is the exact issue here, but it is probably something related to redirection.

It is probably a bug in zimdump.

**Comment by Dalton-Overlin** [comment]
Is there an argument to pass to zimdump to output debug data? That way I could share the debug data here if that's an option?

**Comment by kelson42** [comment]
@Dalton-Overlin Not so far I know, we have here a bug IMO zimdump. This will be fixed soon, but this still might take a few weeks. We are really commited to allow a proper dumping of WPEN full and this is why we currently work to revamp the zimdump tool.

**Comment by Dalton-Overlin** [comment]
Sounds good, I will be patient and wait for the bug fix to emerge and then try again. Would you like me to close this thread (since your aware of the bug) or leave it open until the bug is formally fixed?

**Comment by kelson42** [comment]
@Dalton-Overlin Thx, wee need to keep that ticket open.

**Comment by Dalton-Overlin** [comment]
@kelson42 Your welcome, sounds good. :)

**Comment by kelson42** [comment]
@Dalton-Overlin BTW, which version of the zimdump do you use?

**Comment by Dalton-Overlin** [comment]
@kelson42 Sorry for the delayed response, I am using the zimdump version that's present in zim-tools 1.2.1. From this release: https://github.com/openzim/zim-tools/releases/tag/1.2.1

**Comment by kelson42** [comment]
@Dalton-Overlin Thank you for your patience on this ticket. The ZIM file you deal with is a bit old and we have released a new one from the same content... but updated at http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2020-06.zim. We have as well made massive improvements on zimdump and even if not released yet, it is available at nightly here http://download.openzim.org/nightly/2020-06-12/zim-tools_linux-x86_64-2020-06-12.tar.gz. Our recommendation would be to try again with latest tools and ZIM file. If it still fail, we would start the investigation from here. Would you be able to do that?

**Comment by Dalton-Overlin** [comment]
@kelson42 Your welcome and I did as you asked. I downloaded the new ZIM file, the nightly build, used the new zimdump, and good news! It works as expected! Using Ubuntu 18.04 LTS x64 to run zimdump, the files extracted as they should, they are viewable, and it yielded no errors when using the new nightly build. I thank you all very much for taking the time to work on and fix the issue, I really appreciate it. Since this issue appears to be fixed, would you like me to close this issue now or wait?

**Comment by kelson42** [comment]
Great news. Yes we can close the ticket.
